{
  "hash": "c24c073dd54d42423400d585387cc2fb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 4: Factorial Treatment Structure\"\nsubtitle: \"Analyzing a Factorial\"\nformat: \n  revealjs:\n    # theme: simple # other modern-ish options: dark, simple, solarized\n    theme: simple\n    slide-number: c/t \n    # chalkboard: true # lets you draw on top of slides (keyboard: c) or open a board (b)\n    width: 1200\n    height: 675\n    css: modern-slides.css\n    auto-stretch: false\n    html-math-method: mathjax\n# format: \n#   html:\n#     toc: true\n#   pdf:\n#     toc: false\nexecute: \n  warning: false\n  message: false\n  echo: false\n---\n# Analyzing a Factorial: Model, ANOVA, and Decision Flow\n\n## Example 4.2: Bakery\n\n```{=html}\n<style>\n.reveal .slides .small table { font-size: 0.78em; line-height:1.05; }\n.reveal .slides .small table th, .reveal .slides .small table td { padding:6px 8px; }\n</style>\n```\n\n::::: columns\n::: column\n**Treatment Structure:** 3 x 2 Full Factorial\n\n-   Shelf Height (Bottom, Middle, Top)\n-   Shelf Width (Regular, Wide)\n\n**Design Structure:** CRD with r = 2 stores per treatment combination.\n\n**Response:** Bread Sales\n:::\n\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](_images/042-bakerys.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n:::::\n\n## What changes when we add a factor?\n\n-   We add:\n    -   Another main effect\n    -   An interaction term\n-   We must decide what effects are present *before* interpreting the treatment means.\n\n> The goal of the analysis is to decide which effects matter.\n\n## The Treatment Effects Model (Two-way Factorial)\n\n<span style=\"font-size:0.7em\"> $$y_{ijk}=\\mu+\\alpha_i+\\beta_j+\\alpha\\beta_{ij}+\\epsilon_{ijk} \\text{ with } \\epsilon_{ijk} \\sim \\text{ iid }N(0,\\sigma^2)$$\n</span>\n\n<span style=\"font-size:0.7em\">\n$$\\text{for } i=1,2,3,…,a; j=1,2,…,b;   k=1,2,….,r$$\n</span>\n\n- <span style=\"font-size:0.7em\">$y_{ijk}$: is the response (sales) from the $k^{th}$ experimental unit (store) using the $i^{th}$ level of Factor A (height) and $j^{th}$ level of Factor B (width) combination</span>\n-   <span style=\"font-size:0.7em\">$\\mu$: is the grand/overall mean sales</span>\n-   <span style=\"font-size:0.7em\">$\\alpha_i$: is the effect of the $i^{th}$ level of factor A (height)</span>\n-   <span style=\"font-size:0.7em\">$\\beta_j$: is the effect of the $j^{th}$ level of factor B (width)</span>\n-   <span style=\"font-size:0.7em\">$\\alpha\\beta_{ij}$: is the interaction effect between the $i^{th}$ level of A (height) and $j^{th}$ level of B (width)</span>\n-   <span style=\"font-size:0.7em\">$\\epsilon_{ijk}$: the experimental error associated with the $k^{th}$ experimental unit (store) using the $i^{th}$ level of Factor A (height) and $j^{th}$ level of Factor B (width) combination </span>\n\n## ANOVA for Two-way Factorials\n\nJust like one-way ANOVA: $SST = SSTrt + SSE$\n\nFor a factorial: $SSTrt = SSA + SSB + SSAB$\n\n-   Main effect of factor A (Height): $SSA = rb\\sum_i(\\bar y_{i\\cdot\\cdot}-\\bar y_{\\cdot\\cdot\\cdot})^2$\n-   Main effect of factor B (Width): $SSB = ra\\sum_j(\\bar y_{\\cdot j\\cdot}-\\bar y_{\\cdot\\cdot\\cdot})^2$\n-   AB Interaction Effect (Height x Width): $SSAB = SST - SSE - SSA - SSB$\n\n## Full ANOVA Table (Two-way) {.small}\n\n| Source (SV) | df | SS | MS | F |   |\n|----|----|----|----|----|----|\n| A | $a-1$ | SSA | MSA $=\\frac{SSA}{a-1}$ | $\\frac{MSA}{MSE}$ | Do avg sales differ across shelf heights? |\n| B | $b-1$ | SSB | MSB $=\\frac{SSB}{b-1}$ | $\\frac{MSB}{MSE}$ | Do avg sales differ across shelf widths? |\n| AB | $(a-1)(b-1)$ | SSAB | MSAB $=\\frac{SSAB}{(a-1)(b-1)}$ | $\\frac{MSAB}{MSE}$ | Does the effect of width *depend* on height? |\n| Error: e.u.(AB) | $(r-1)ab$ | SSE | MSE $=\\frac{SSE}{(r-1)ab}$ |  |  |\n| Total | $N-1$ | SST |  |  |  |\n\n## Decision Flowchart\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](_images/two-way-decision-flowchart.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## What are we testing?\n\n**Interaction**\n\n$$H_0:\\text{ All } \\alpha\\beta_{ij} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha\\beta_{ij} \\ne 0$$\n\n**Main Effect of A**\n\n$$H_0:\\text{ All } \\alpha_{i} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha_{i} \\ne 0$$\n\n**Main Effect of B**\n\n$$H_0:\\text{ All } \\beta_{j} = 0 \\text{  vs  } H_A: \\text{At least one } \\beta_{j} \\ne 0$$\n\n## Example 4.2: Skeleton ANOVA\n\n| Source of Variation | DF = 12 stores - 1 = 11 total df |\n|---------------------|----------------------------------|\n|                     |                                  |\n\n## R: Fitting the Model\n\nLet's prep the data...\n\n::: columns\n\n:::{.column width=65%}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbakery_data <- read_csv(\"_data/04-bakery_data.csv\") |>  \n  mutate(height = factor(height, \n                         levels = c(\"bottom\", \"middle\", \"top\")),\n         width = factor(width, levels = c(\"regular\", \"wide\")))\n\nhead(bakery_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  height width   sales placement    \n  <fct>  <fct>   <dbl> <chr>        \n1 bottom regular    47 bottomregular\n2 bottom regular    43 bottomregular\n3 bottom wide       46 bottomwide   \n4 bottom wide       40 bottomwide   \n5 middle regular    62 middleregular\n6 middle regular    68 middleregular\n```\n\n\n:::\n:::\n\n:::\n\n:::{.column width=35%}\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(bakery_data$height)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"bottom\" \"middle\" \"top\"   \n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(bakery_data$width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"regular\" \"wide\"   \n```\n\n\n:::\n:::\n\n:::\n:::\n## R: Fitting the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\nbakery_mod <- lm(sales ~ height + width + height:width, data = bakery_data)\n```\n:::\n\n\n::::: columns\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(bakery_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: sales\n             Df Sum Sq Mean Sq F value    Pr(>F)    \nheight        2   1544  772.00 74.7097 5.754e-05 ***\nwidth         1     12   12.00  1.1613    0.3226    \nheight:width  2     24   12.00  1.1613    0.3747    \nResiduals     6     62   10.33                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bakery_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ height + width + height:width, data = bakery_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n    -3     -2      0      2      3 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      51.000      0.928  54.959 2.44e-09 ***\nheight1          -7.000      1.312  -5.334  0.00177 ** \nheight2          16.000      1.312  12.192 1.85e-05 ***\nwidth1           -1.000      0.928  -1.078  0.32261    \nheight1:width1    2.000      1.312   1.524  0.17835    \nheight2:width1   -1.000      1.312  -0.762  0.47494    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.215 on 6 degrees of freedom\nMultiple R-squared:  0.9622,\tAdjusted R-squared:  0.9308 \nF-statistic: 30.58 on 5 and 6 DF,  p-value: 0.0003384\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n\n## Recall, \"sum to zero\" {.small}\n\n$\\hat\\mu =$\n\n::::: columns\n::: column\n| Height |                   |\n|--------|-------------------|\n| Bottom | $\\hat\\alpha_1=7$  |\n| Middle | $\\hat\\alpha_2=16$ |\n| Top    | $\\hat\\alpha_3=$   |\n:::\n\n::: column\n| Width   |                  |\n|---------|------------------|\n| Regular | $\\hat\\beta_1=-1$ |\n| Wide    | $\\hat\\beta_2=$   |\n:::\n:::::\n\n|            | Regular                         | Wide                          |\n|------------|---------------------------------|-------------------------------|\n| **Bottom** | $\\widehat{\\alpha\\beta}_{11}=2$  | $\\widehat{\\alpha\\beta}_{12}=$ |\n| **Middle** | $\\widehat{\\alpha\\beta}_{21}=-1$ | $\\widehat{\\alpha\\beta}_{22}=$ |\n| **Top**    | $\\widehat{\\alpha\\beta}_{31}=$   | $\\widehat{\\alpha\\beta}_{32}=$ |\n\n## Decomposition of Model Effects\n\n<span style=\"font-size:0.75em\">Recall our statistical effects model: $y_{ijk} = \\mu +\\alpha_i +\\beta_j + \\alpha\\beta_{ij} + \\epsilon_{ijk}$</span>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-8-1.png){width=70%}\n:::\n:::\n\n\n## Model Diagnostics\n\n\n::::: columns\n::: column\n\n::: {.cell code-folding='true'}\n\n```{.r .cell-code}\nbakery_mod |> \n  broom::augment() |> \n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_hline(yintercept = 0,\n             color = \"#3a86d4\") +\n  labs(x = \"Fitted Values\", y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell code-folding='true'}\n\n```{.r .cell-code}\nbakery_mod |> \n  broom::augment() |> \n  ggpubr::ggqqplot(x = \".resid\",\n         color = \"#3a86d4\") +\n  labs(title = \"Normal QQ-Plot of Residuals\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n\n# Example: No Interaction, interpret Main Effects\n\n\n## Example 4.2: Bakery\n\n```{=html}\n<style>\n.reveal .slides .small table { font-size: 0.78em; line-height:1.05; }\n.reveal .slides .small table th, .reveal .slides .small table td { padding:6px 8px; }\n</style>\n```\n\n::::: columns\n::: column\n**Treatment Structure:** 3 x 2 Full Factorial\n\n-   Shelf Height (Bottom, Middle, Top)\n-   Shelf Width (Regular, Wide)\n\n**Design Structure:** CRD with r = 2 stores per treatment combination.\n\n**Response:** Bread Sales\n:::\n\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](_images/042-bakerys.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n:::::\n\n## The Treatment Effects Model (Two-way Factorial)\n\n<span style=\"font-size:0.7em\"> $$y_{ijk}=\\mu+\\alpha_i+\\beta_j+\\alpha\\beta_{ij}+\\epsilon_{ijk} \\text{ with } \\epsilon_{ijk} \\sim \\text{ iid }N(0,\\sigma^2)$$\n</span>\n\n<span style=\"font-size:0.7em\">\n$$\\text{for } i=1,2,3,…,a; j=1,2,…,b;   k=1,2,….,r$$\n</span>\n\n- <span style=\"font-size:0.7em\">$y_{ijk}$: is the response (sales) from the $k^{th}$ experimental unit (store) using the $i^{th}$ level of Factor A (height) and $j^{th}$ level of Factor B (width) combination</span>\n-   <span style=\"font-size:0.7em\">$\\mu$: is the grand/overall mean sales</span>\n-   <span style=\"font-size:0.7em\">$\\alpha_i$: is the effect of the $i^{th}$ level of factor A (height)</span>\n-   <span style=\"font-size:0.7em\">$\\beta_j$: is the effect of the $j^{th}$ level of factor B (width)</span>\n-   <span style=\"font-size:0.7em\">$\\alpha\\beta_{ij}$: is the interaction effect between the $i^{th}$ level of A (height) and $j^{th}$ level of B (width)</span>\n-   <span style=\"font-size:0.7em\">$\\epsilon_{ijk}$: the experimental error associated with the $k^{th}$ experimental unit (store) using the $i^{th}$ level of Factor A (height) and $j^{th}$ level of Factor B (width) combination </span>\n\n## Decision Flowchart\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](_images/two-way-decision-flowchart.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## What are we testing?\n\n**Interaction**\n\n$$H_0:\\text{ All } \\alpha\\beta_{ij} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha\\beta_{ij} \\ne 0$$\n\n**Main Effect of A**\n\n$$H_0:\\text{ All } \\alpha_{i} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha_{i} \\ne 0$$\n\n**Main Effect of B**\n\n$$H_0:\\text{ All } \\beta_{j} = 0 \\text{  vs  } H_A: \\text{At least one } \\beta_{j} \\ne 0$$\n\n## ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\nbakery_mod <- lm(sales ~ height + width + height:width, data = bakery_data)\nanova(bakery_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: sales\n             Df Sum Sq Mean Sq F value    Pr(>F)    \nheight        2   1544  772.00 74.7097 5.754e-05 ***\nwidth         1     12   12.00  1.1613    0.3226    \nheight:width  2     24   12.00  1.1613    0.3747    \nResiduals     6     62   10.33                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n## Do these results make sense?\n\nInspecting the interaction plot between height and width on bread sales, does there visually appear to be a significant interaction?\n\n\n::: {.cell layout-align=\"center\" height='\"NA\"' width='4'}\n\n```{.r .cell-code  code-fold=\"true\"}\nemmip(bakery_mod, width ~ height, CIs = TRUE, adjust = \"tukey\") +\n  labs(y = \"Bread Sales\",\n       x = \"height\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n## Where should we proceed?\n\n1. Interaction: We do not have enough evidence of a significant interaction effect between shelf height and shelf width on bread sales (F = 1.16; df = 2,6; p = 0.375).\n2. Width Main: We do not have enough evidence of a significant main effect of shelf width on bread sales (F = 1.16; df = 1,6; p = 0.323).\n3. **Height Main**: We do have evidence of a significant main effect of height on bread sales (F = 74.7; df = 2, 6; p < 0.0001).\n \n > What are the marginal mean sales for each height (sig main effect)?\n > Which heights differ?\n \n## R: Marginal Height LSMEANS\n\n:::: columns\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nheight_lsmeans <- emmeans(bakery_mod, specs = ~ height) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: Results may be misleading due to involvement in interactions\n```\n\n\n:::\n\n```{.r .cell-code}\nheight_lsmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n height emmean   SE df lower.CL upper.CL\n bottom     44 1.61  6     40.1     47.9\n middle     67 1.61  6     63.1     70.9\n top        42 1.61  6     38.1     45.9\n\nResults are averaged over the levels of: width \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nemmip(bakery_mod, ~ height, CIs = TRUE, adjust = \"tukey\") +\n  labs(y = \"Bread Sales\",\n       x = \"height\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-16-1.png){width=480}\n:::\n:::\n\n:::\n::::\n\n## R: Height pairwise comparisons\n\n:::: columns\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(height_lsmeans, \n      adjust = \"tukey\", infer = c(T,T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast        estimate   SE df lower.CL upper.CL t.ratio p.value\n bottom - middle      -23 2.27  6   -29.97   -16.03 -10.119  0.0001\n bottom - top           2 2.27  6    -4.97     8.97   0.880  0.6714\n middle - top          25 2.27  6    18.03    31.97  10.999 <0.0001\n\nResults are averaged over the levels of: width \nConfidence level used: 0.95 \nConf-level adjustment: tukey method for comparing a family of 3 estimates \nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\ncld(height_lsmeans, \n    decreasing = F, Letters = LETTERS, \n    adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n height emmean   SE df lower.CL upper.CL .group\n top        42 1.61  6     36.7     47.3  A    \n bottom     44 1.61  6     38.7     49.3  A    \n middle     67 1.61  6     61.7     72.3   B   \n\nResults are averaged over the levels of: width \nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 3 estimates \nP value adjustment: tukey method for comparing a family of 3 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n:::\n::::\n\n\n## What can we conclude?\n\n+ For bread placed on the middle shelf, the estimated mean bread sales is 67 (s.e. = 1.61).\n+ This is estimated to be 25 more sales than for bread placed on the top shelf (t = 10.99; df = 6; p < 0.0001) and 23 more sales than for bread placed on the bottom shelf (t = 10.12; df = 6; p = 0.0001).\n\n\n# Example: Interaction Present, interpret Simple Effects\n\n\n## Example 4.3: Asphalt\n\n> A civil engineer conducted an experiment to evaluate differences among a set of compaction methods for their effect on the tensile strength of test specimens and to determine to what extent the aggregate type affected the comparisons among the compaction methods.  Twenty-four specimens of the asphalt concrete were constructed, and the eight treatment combinations were randomly assigned to the specimens.\n>\n> Example 6.2 from Design of Experiments: Statistical Principles of Research Design and Analysis, 2nd Edition by Robert O. Kuehl.  \n\n## Example 4.3: Asphalt\n\n:::: columns\n::: column\n**Factors:**\n+ *Aggregate Type:* Basalt, Silicous\n+ *Compaction Method:* Static, Regular kneading, Low kneading, Very low kneading\n\n**Design:** CRD with $r=3$ specimens per treatment combination (N = 24)\n\n**Response:** Tensile strength\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasphalt_data <- read_csv(\"_data/04-asphalt_data.csv\") |>\n  mutate(aggregate  = factor(aggregate),\n         compaction = factor(compaction))\n```\n:::\n\n::: {style=\"font-size: 50%;\"}\nNote: Because we didn't specify `levels =` in `factor()`, the levels of `aggregagte` and `compation` are in alphabetical order\n:::\n\n:::\n::: column\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(asphalt_data)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:200px; \"><table class=\"table\" style=\"font-size: 20px; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> aggregate </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> compaction </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> strength </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> basalt </td>\n   <td style=\"text-align:left;\"> static </td>\n   <td style=\"text-align:right;\"> 68 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> basalt </td>\n   <td style=\"text-align:left;\"> static </td>\n   <td style=\"text-align:right;\"> 63 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> basalt </td>\n   <td style=\"text-align:left;\"> static </td>\n   <td style=\"text-align:right;\"> 65 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> basalt </td>\n   <td style=\"text-align:left;\"> regular </td>\n   <td style=\"text-align:right;\"> 126 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> basalt </td>\n   <td style=\"text-align:left;\"> regular </td>\n   <td style=\"text-align:right;\"> 128 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(asphalt_data$aggregate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"basalt\"   \"siliciou\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(asphalt_data$compaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"low\"     \"regular\" \"static\"  \"verylow\"\n```\n\n\n:::\n:::\n\n\n\n\n:::\n::::\n\n## Example 4.3: Statistical Effects Model\n\n<span style=\"font-size:0.7em\"> $$y_{ijk}=\\mu+\\alpha_i+\\beta_j+\\alpha\\beta_{ij}+\\epsilon_{ijk} \\text{ with } \\epsilon_{ijk} \\sim \\text{ iid }N(0,\\sigma^2)$$\n</span>\n\n<span style=\"font-size:0.7em\">\n$$\\text{for } i=1,2; j=1,2,3,4;   k=1,2,3$$\n</span>\n\n- <span style=\"font-size:0.7em\">$y_{ijk}$: is the observed tensile strength for the $k^{th}$s specimen receiving the $i^{th}$ Aggregate and $j^{th}$ Compaction</span>\n-   <span style=\"font-size:0.7em\">$\\mu$: is the overall mean tensile strength</span>\n-   <span style=\"font-size:0.7em\">$\\alpha_i$: is the effect of the $i^{th}$ level of Aggregate</span>\n-   <span style=\"font-size:0.7em\">$\\beta_j$: is the effect of the $j^{th}$ level of Compaction</span>\n-   <span style=\"font-size:0.7em\">$\\alpha\\beta_{ij}$: is the interaction effect between the $i^{th}$ level of Aggregate and $j^{th}$ level of Compaction</span>\n-   <span style=\"font-size:0.7em\">$\\epsilon_{ijk}$: the experimental error associated with the $k^{th}$ specimen receiving the $i^{th}$ Aggregate and $j^{th}$ Compaction</span>\n\n## Decision Flowchart\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](_images/two-way-decision-flowchart.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## ANOVA\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\nasphalt_mod <- lm(strength ~ aggregate*compaction, data = asphalt_data)\nanova(asphalt_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: strength\n                     Df Sum Sq Mean Sq F value    Pr(>F)    \naggregate             1   1734  1734.0 182.526 3.628e-10 ***\ncompaction            3  16244  5414.5 569.947 < 2.2e-16 ***\naggregate:compaction  3   1145   381.7  40.175 1.124e-07 ***\nResiduals            16    152     9.5                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nWe have evidence to conclude there is a significant interaction between aggregate and compaction on tensile strength (F = 1145; df = 3,16; p < 0.0001).\n\n> The effect of aggregate on tensile strength varies across different levels of compaction.\n\n## Where should we proceed?\n\n1. **Interaction:** We have evidence to conclude there is a significant interaction between aggregate and compaction on tensile strength (F = 1145; df = 3,16; p < 0.0001).\n2. Aggregate Main: don't care.. misleading.\n3. Compaction Main: don't care.. misleading.\n \n > How does the mean tensile strength for aggregates change depending on the compaction method?\n >\n > What combination of aggregate and compaction lead to higher tensile strengths?\n \n## R: Interaction Plots\n\n:::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\nemmip(asphalt_mod, \n      aggregate ~ compaction, \n      CIs = TRUE, adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n::: column\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmip(asphalt_mod, \n      compaction ~ aggregate, \n      CIs = TRUE, adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-26-1.png){fig-align='center' width=576}\n:::\n:::\n\n:::\n::::\n\n## Joint Pairwise Comparisons: Aggregate x Compaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multcomp)\naxc_lsmeans <- emmeans(asphalt_mod, specs = ~ aggregate*compaction)\ncld(axc_lsmeans, Letters = LETTERS, decreasing = T, adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n aggregate compaction emmean   SE df lower.CL upper.CL .group \n basalt    regular     129.0 1.78 16    123.4    134.6  A     \n siliciou  regular     111.0 1.78 16    105.4    116.6   B    \n basalt    low          97.3 1.78 16     91.8    102.9    C   \n siliciou  static       67.7 1.78 16     62.1     73.2     D  \n basalt    static       65.3 1.78 16     59.8     70.9     DE \n siliciou  low          60.7 1.78 16     55.1     66.2     DE \n basalt    verylow      57.3 1.78 16     51.8     62.9      E \n siliciou  verylow      41.7 1.78 16     36.1     47.2       F\n\nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 8 estimates \nP value adjustment: tukey method for comparing a family of 8 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n\n## R: Aggregate | Compaction {.scrollable}\n\n:::: columns\n::: column\n**Slice Tests**\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoint_tests(axc_lsmeans, \n            by = \"compaction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncompaction = low:\n model term df1 df2 F.ratio p.value\n aggregate    1  16 212.281 <0.0001\n\ncompaction = regular:\n model term df1 df2 F.ratio p.value\n aggregate    1  16  51.158 <0.0001\n\ncompaction = static:\n model term df1 df2 F.ratio p.value\n aggregate    1  16   0.860  0.3676\n\ncompaction = verylow:\n model term df1 df2 F.ratio p.value\n aggregate    1  16  38.754 <0.0001\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmip(asphalt_mod, \n      compaction ~ aggregate, \n      CIs = TRUE, \n      adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n::: column\n\n**Simple Effects**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(asphalt_mod, specs = ~ aggregate | compaction) |> \n  pairs(adjust = \"tukey\", infer = c(T,T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncompaction = low:\n contrast          estimate   SE df lower.CL upper.CL t.ratio p.value\n basalt - siliciou    36.67 2.52 16    31.33     42.0  14.570 <0.0001\n\ncompaction = regular:\n contrast          estimate   SE df lower.CL upper.CL t.ratio p.value\n basalt - siliciou    18.00 2.52 16    12.67     23.3   7.152 <0.0001\n\ncompaction = static:\n contrast          estimate   SE df lower.CL upper.CL t.ratio p.value\n basalt - siliciou    -2.33 2.52 16    -7.67      3.0  -0.927  0.3676\n\ncompaction = verylow:\n contrast          estimate   SE df lower.CL upper.CL t.ratio p.value\n basalt - siliciou    15.67 2.52 16    10.33     21.0   6.225 <0.0001\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n::::\n\n## R: Compaction | Aggregate\n\n:::: columns\n::: column\n**Slice Tests**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njoint_tests(axc_lsmeans, by = \"aggregate\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naggregate = basalt:\n model term df1 df2 F.ratio p.value\n compaction   3  16 338.956 <0.0001\n\naggregate = siliciou:\n model term df1 df2 F.ratio p.value\n compaction   3  16 271.167 <0.0001\n```\n\n\n:::\n\n```{.r .cell-code}\nemmip(asphalt_mod, aggregate ~ compaction, CIs = TRUE, adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.2-analyzing-a-factorial_files/figure-revealjs/unnamed-chunk-31-1.png){fig-align='center' width=60%}\n:::\n:::\n\n:::\n::: column\n\n**Simple Effects**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(asphalt_mod, specs = ~ compaction | aggregate) |> \n  pairs(adjust = \"tukey\", infer = c(T,T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naggregate = basalt:\n contrast          estimate   SE df lower.CL upper.CL t.ratio p.value\n low - regular        -31.7 2.52 16    -38.9    -24.5 -12.583 <0.0001\n low - static          32.0 2.52 16     24.8     39.2  12.716 <0.0001\n low - verylow         40.0 2.52 16     32.8     47.2  15.894 <0.0001\n regular - static      63.7 2.52 16     56.5     70.9  25.299 <0.0001\n regular - verylow     71.7 2.52 16     64.5     78.9  28.477 <0.0001\n static - verylow       8.0 2.52 16      0.8     15.2   3.179  0.0269\n\naggregate = siliciou:\n contrast          estimate   SE df lower.CL upper.CL t.ratio p.value\n low - regular        -50.3 2.52 16    -57.5    -43.1 -20.000 <0.0001\n low - static          -7.0 2.52 16    -14.2      0.2  -2.782  0.0582\n low - verylow         19.0 2.52 16     11.8     26.2   7.550 <0.0001\n regular - static      43.3 2.52 16     36.1     50.5  17.219 <0.0001\n regular - verylow     69.3 2.52 16     62.1     76.5  27.550 <0.0001\n static - verylow      26.0 2.52 16     18.8     33.2  10.331 <0.0001\n\nConfidence level used: 0.95 \nConf-level adjustment: tukey method for comparing a family of 4 estimates \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n:::\n::::\n",
    "supporting": [
      "04.2-analyzing-a-factorial_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}