{
  "hash": "38fdf2765f413b99404bf21d0599338f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 2: Completely Randomized Designs\"\nsubtitle: \"Inference and Contrasts\"\nformat: \n  revealjs:\n    # theme: simple # other modern-ish options: dark, simple, solarized\n    theme: simple\n    slide-number: c/t \n    chalkboard: true # lets you draw on top of slides (keyboard: c) or open a board (b)\n    width: 1200\n    height: 675\n    css: modern-slides.css\n    auto-stretch: false\n# format: \n#   html:\n#     toc: true\n#   pdf:\n#     toc: false\nexecute: \n  warning: false\n  message: false\n---\n\n# Infernce for Treatment Means\n\n## Inference for Treatment Means\n\nANOVA tells us whether *any* means differ.\n\nNow we want:\n\n- Estimates of each treatment mean ($\\mu_i$)\n- Uncertainty of those treatment means (SEs + CIs)  \n- Interpretation in context\n\n## Example 2.1: Running Shoes\n\n\n\n:::: columns\n::: column\n**Response:** Lap time (seconds)\n\n**Treatment structure:** \n\n+ One-way\n+ Factor: Shoe type \n+ 3 Levels: control, lightweight, and stability\n+ t = 3\n:::\n::: column\n**Experimental structure:** \n\n+ CRD\n+ Experimental Unit: Individual (n = 6, r = 2) \n+ Measurement Unit: Individual (N = 6)\n:::\n::::\n\n**Goal:** Determine whether shoe type affects mean lap time.\n\n## Example 2.1: Running Shoes (Blueprint)\n\n![](_images/021-blueprint-shoe-type.png){width=55%}\n\n## Example 2.1: Running Shoes (Effects Model)\n\n$$y_{ij} = \\mu + \\tau_i + \\varepsilon_{ij} \\text{ with } \\varepsilon_{ij} \\text{ iid } \\sim N(0, \\sigma^2)$$\nfor \t$i = 1, 2, 3$ and $j = 1, 2$\n\nWhere:\n\n+ $y_{ij}$ - the *observed* lap time for the $j^{th}$ runner wearing the $i^{th}$ shoe type.\n\n+\t$\\mu$ - the overall mean lap time.\n\n+ $\\tau_i$ - the effect of the $i^{th}$ shoe type.\n\n+\t$\\epsilon_{ij}$ - the experimental error associated with the $j^{th}$ runner wearing the $i^{th}$ shoe type.\n\n## What we Estimated {.scrollable}\n\nModel Reminder: $y_{ij} = \\mu + \\tau_i + \\varepsilon_{ij}$ \n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\n\nshoe_mod <- lm(lap_time_seconds ~ shoe, data = shoe_data)\n\nanova(shoe_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: lap_time_seconds\n          Df Sum Sq Mean Sq F value  Pr(>F)  \nshoe       2    172      86    21.5 0.01666 *\nResiduals  3     12       4                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(shoe_data$shoe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Control\"     \"Lightweight\" \"Stability\"  \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(shoe_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = lap_time_seconds ~ shoe, data = shoe_data)\n\nResiduals:\n 1  2  3  4  5  6 \n-1  1 -1  1  2 -2 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  62.0000     0.8165  75.934 5.03e-06 ***\nshoe1        -1.0000     1.1547  -0.866  0.45018    \nshoe2         7.0000     1.1547   6.062  0.00901 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2 on 3 degrees of freedom\nMultiple R-squared:  0.9348,\tAdjusted R-squared:  0.8913 \nF-statistic:  21.5 on 2 and 3 DF,  p-value: 0.01666\n```\n\n\n:::\n:::\n\n\n\n\n## Estimating Treatment Means $\\hat \\mu_i$ (Balanced CRD)\n\nFrom the data, each treatment has a sample mean:\n\n$$\\bar y_{i\\cdot}$$\n\nFrom the model, each treatment has an estimated *least squares mean*:\n\n$$\\hat\\mu_i = \\hat\\mu + \\hat\\tau_i$$\n\nIn a **balanced** CRD (i.e., each treatment has $r$ replications), these are the same quantity:\n\n$$\\hat\\mu_i = \\bar y_{i\\cdot}$$\n\n## Sampling Variability of $\\bar y_{i\\cdot}$\n\nUnder the model:\n\n$$Var(\\bar y_{i\\cdot}) = \\frac{\\sigma^2}{r}$$\n\nWe don’t know $\\sigma^2$, so we estimate it with:\n\n$$\\widehat{\\sigma}^2 = MSE$$\n\n## Standard Error of a Treatment Mean $SE(\\hat \\mu_i)$\n\nBalanced CRD (each treatment has $r$ replications):\n\n$$SE(\\hat\\mu_i) = \\sqrt{\\frac{MSE}{r}}$$\n\n## Degrees of Freedom\n\nAll inference uses the **error degrees of freedom**:\n\n$$df_E = N - t = (r-1)t$$\n\nThis is the same df used for the F-test in ANOVA.\n\n## Confidence Interval for a Treatment Mean\n\nA CI for $\\mu_i$:\n\n$$\\hat\\mu_i \\pm t^*_{df_E, \\alpha/2}\\;SE(\\hat\\mu_i)$$\n\nwhere $t^*$ comes from the t distribution with $df_E = N-t = (r-1)t$ and the $\\alpha/2$ quantile associated with the confidence level.\n\n## R: Estimated Means + SE + CI\n\n:::: columns\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nshoe_lsmeans <- emmeans(shoe_mod, specs = ~ shoe)\nshoe_lsmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n shoe        emmean   SE df lower.CL upper.CL\n Control         61 1.41  3     56.5     65.5\n Lightweight     69 1.41  3     64.5     73.5\n Stability       56 1.41  3     51.5     60.5\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nemmip(shoe_mod, ~ shoe, CIs = T) +\n  labs(y = \"Estimated Lap Time (seconds)\")\n```\n\n::: {.cell-output-display}\n![](02.2-crd-contrasts_files/figure-revealjs/unnamed-chunk-4-1.png){width=60%}\n:::\n:::\n\n:::\n::::\n\n## Interpretation of Results\n\nThe estimated mean 400m lap time for runners wearing the control shoe is 61 seconds (s.e. = 1.41). \n\nWe are 95% confident the population mean 400m lap time for all runners wearing the control shoe is between 56.5 and 65.5 seconds.\n   \nThese results apply to all runner similar to those in our study under similar conditions.\n\n\n\n\n# Contrasts\n\n## From Means to Comparisons\n\nANOVA tells us whether *any* means differ.\n\nInference for means tells us *what each mean looks like*.\n\n**Contrasts let us ask specific questions about those means.**\n\n## What Is a Contrast?\n\n::: callout-note\nA **contrast** is a linear combination of treatment means:\n\n$$\nC = c_1 \\mu_1 + c_2 \\mu_2 + \\cdots + c_t \\mu_t\n$$\n\nwith the constraint:\n\n$$\n\\sum_{i=1}^t c_i = 0\n$$\n:::\n\n## What We Actually Estimate\n\nWe estimate contrasts using the estimated least squares means $\\hat \\mu_i$:\n\n$$\n\\hat C = c_1 \\hat\\mu_1 + c_2\\hat\\mu_2 + \\cdots + c_t \\hat\\mu_t\n$$\n\n## Example 2.1: Running Shoes\n\n\n:::: columns\n::: column\n**Response:** Lap time (seconds)\n\n**Treatment structure:** \n\n+ One-way\n+ Factor: Shoe type \n+ 3 Levels: control, lightweight, and stability\n+ t = 3\n:::\n::: column\n**Experimental structure:** \n\n+ CRD\n+ Experimental Unit: Individual (r = 2) \n+ Measurement Unit: Individual (N = 6)\n:::\n::::\n\n## Example 2.1: Running Shoes ($\\hat \\mu_i$ + $\\hat \\sigma^2$)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(shoe_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: lap_time_seconds\n          Df Sum Sq Mean Sq F value  Pr(>F)  \nshoe       2    172      86    21.5 0.01666 *\nResiduals  3     12       4                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nshoe_lsmeans <- emmeans(shoe_mod, specs = ~ shoe)\nshoe_lsmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n shoe        emmean   SE df lower.CL upper.CL\n Control         61 1.41  3     56.5     65.5\n Lightweight     69 1.41  3     64.5     73.5\n Stability       56 1.41  3     51.5     60.5\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n## Contrast 1: Lightweight vs Stability\n\n> Does the mean lap time differ between lightweight and stability shoes?\n\n> $H_0:$\n\n> $H_A:$\n\n\nContrast:\n\n$C =$ \n\nCoefficients: $(0,\\;1,\\;-1)$\n\n\n## Standard Error of a Contrast (Balanced CRD)\n\n::: callout-note\nFor a balanced CRD with $r$ replications per treatment:\n\n$$\nSE(\\hat C) = \\sqrt{ MSE \\sum_{i=1}^t \\frac{c_i^2}{r} }\n$$\n:::\n\n## Hypothesis Test for a Contrast\n\n$$\nH_0: \\mu_2-\\mu_3 = 0\n\\qquad\\text{vs}\\qquad\nH_A: \\mu_2-\\mu_3 \\neq 0\n$$\n\nTest statistic:\n\n$$\nt = \\frac{\\hat C}{SE(\\hat C)}\n$$\n\nwith $df = (r-1)t$.\n\n## Confidence Interval for a Contrast\n\nA CI for $C$:\n\n$$\n\\hat C \\pm t^*_{(r-1)t,\n\\alpha/2} \\; SE(\\hat C)\n$$\n\n## R: Contrasts {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshoe_mod <- lm(lap_time_seconds ~ shoe, data = shoe_data)\nshoe_lsmeans <- emmeans(shoe_mod, ~ shoe)\nlevels(shoe_data$shoe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Control\"     \"Lightweight\" \"Stability\"  \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(shoe_lsmeans,\n         method = list(\"Lightweight vs Stability\" = c(0, 1, -1)),\n         infer = c(TRUE, TRUE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                 estimate SE df lower.CL upper.CL t.ratio p.value\n Lightweight vs Stability       13  2  3     6.64     19.4   6.500  0.0074\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n\n## Interpretation: Lightweight vs Stability\n\nAt an $\\alpha = 0.05$, we have evidence to conclude the mean 400m lap time for lightweight shoes is 13 seconds (s.e. = 2) slower than the mean 400m lap time for stability shoes (t = 6.5; df = 3; p = 0.0074).\n\nWe are 95% confident the population mean 400m lap time for lightweight shoes is between 6.64 and 19.4 seconds slower than for stability shoes.\n\nThese results apply to all runner similar to those in our study under similar conditions.\n\n\n## Contrast 2: Average of Control + Stability vs Lightweight\n\n> Is the lightweight shoe different from the average of the other two?\n\n> $H_0:$\n\n> $H_A:$\n\n\nContrast:\n\n$C =$ \n\nCoefficients: $(0.5,\\;-1,\\;0.5)$\n\n## Contrast 2: Average of Control + Stability vs Lightweight\n\n$\\hat C =$\n\n$SE(\\hat C) =$\n\n$t =$\n\n## R: Contrasts {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast(shoe_lsmeans,\n         method = list(\"Control & Stability vs Lightweight\" = c(0.5, -1, 0.5)),\n         infer = c(TRUE, TRUE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                           estimate   SE df lower.CL upper.CL t.ratio\n Control & Stability vs Lightweight    -10.5 1.73  3      -16    -4.99  -6.062\n p.value\n  0.0090\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n::: callout\n*Note: flipping the contrasts arounds just changes the direction of the estimate and t-statistic*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast(shoe_lsmeans,\n         method = list(\"Control & Stability vs Lightweight\" = c(-0.5, 1, -0.5)),\n         infer = c(TRUE, TRUE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                           estimate   SE df lower.CL upper.CL t.ratio\n Control & Stability vs Lightweight     10.5 1.73  3     4.99       16   6.062\n p.value\n  0.0090\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n\n\n## Interpretation: Average of Control + Stability vs Lightweight\n\nAt an $\\alpha = 0.05$, we have evidence to conclude the mean 400m lap time for control and stability shoes combined is 10.5 seconds (s.e. = 1.73) faster than the mean 400m lap time for lightweight shoes (t = -6.06; df = 3; p = 0.009).\n\nWe are 95% confident the population mean 400m lap time for control and stability shoes combined is between 4.99 and 16 seconds faster than for lightweight shoes.\n\nThese results apply to all runner similar to those in our study under similar conditions.\n\n## Preplanned vs Post Hoc Contrasts\n\n**Preplanned contrasts:**\n\n- Chosen before seeing the data  \n- Limited in number  \n- Do not require p-value multiplicity adjustment\n\n**Post hoc contrasts:**\n\n- Chosen after ANOVA  \n- Require multiplicity adjustment\n\n## Why Contrasts Matter\n\nContrasts:\n\n- Align analysis with scientific questions  \n- Avoid unnecessary multiple testing  \n- Provide interpretable comparisons  \n\nThey are often more informative than “all pairwise comparisons.”\n\n# Pairwise Comparisons\n\n## What Are Pairwise Comparisons?\n\n> Which treatment means differ from each other?\n\nPairwise comparisons test:\n\n- $\\mu_1$ vs $\\mu_2$  \n- $\\mu_1$ vs $\\mu_3$  \n- $\\mu_2$ vs $\\mu_3$  \n\nFor $t$ treatments, there are: $\\binom{t}{2} = \\frac{t(t-1)}{2}$ possible pairwise comparisons.\n\n\n## Example 2.1: Running Shoes\n\n\n:::: columns\n::: column\n**Response:** Lap time (seconds)\n\n**Treatment structure:** \n\n+ One-way\n+ Factor: Shoe type \n+ 3 Levels: control, lightweight, and stability\n+ t = 3\n:::\n::: column\n**Experimental structure:** \n\n+ CRD\n+ Experimental Unit: Individual (r = 2) \n+ Measurement Unit: Individual (N = 6)\n:::\n::::\n\n## Example 2.1: Shoes\n\nWith $t = 3$ shoe types:\n\n- Control vs Lightweight  $(H_0: \\mu_1 - \\mu_2 = 0)$\n- Control vs Stability  $(H_0: \\mu_1 - \\mu_3 = 0)$\n- Lightweight vs Stability  $(H_0: \\mu_2 - \\mu_3 = 0)$\n\nThat’s _______ comparisons.\n\n## Pairwise Comparisons as Contrasts\n\nEach pairwise comparison is a contrast:\n\n- Control vs Lightweight: $C = (1, -1, 0)$  \n- Control vs Stability: $C = (1, 0, -1)$  \n- Lightweight vs Stability: $C = (0, 1, -1)$\n\n## The Multiple Testing Problem\n\nEach comparison is a valid t-test.\n\nBut performing *many tests* increases the chance of a:\n\n- Type I error (false positive)\n\nThis is called the *family-wise error rate*.\n\n## Why Error Rates Inflate\n\nSuppose each test uses $\\alpha = 0.05$. Then:\n\n- Probability of *no* false positives (i.e., correctly fail to reject the null): $1-\\alpha = 1 - 0.05 = 0.95$\n  \n- Assuming independence, the probability of all tests leading to *no* false positives: $(1-\\alpha)^\\text{# tests}=(0.95)^3=0.857$\n\n- Probability of *at least one* false positive (i.e., a Type I error): $1-[(1-\\alpha)^\\text{# tests}] = 1-0.857=0.143$.\n\nNote this increases with the number of tests.\n\n## What We Need\n\nWhen doing many comparisons, we want to:\n\n- Control the overall Type I error rate  \n- While still detecting real differences  \n\n**Post Hoc Tests:** adjustments to the p-values (making them larger) and/or confidence intervals (making them wider).\n\n## Fisher’s Protected LSD {.scrollable}\n\n1. First perform the overall ANOVA F-test\n2. Only if F is significant, perform all pairwise t-tests  \n\n::: callout\nNote: From the ANOVA on Example 2.1 Shoe Types: (F = 21.5; df = 2,3; p = 0.017)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshoe_lsmeans <- emmeans(shoe_mod, specs = ~ shoe)\npairs(shoe_lsmeans, infer = c(TRUE, TRUE), adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate SE df lower.CL upper.CL t.ratio p.value\n Control - Lightweight         -8  2  3   -14.36    -1.64  -4.000  0.0280\n Control - Stability            5  2  3    -1.36    11.36   2.500  0.0877\n Lightweight - Stability       13  2  3     6.64    19.36   6.500  0.0074\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(multcomp)\ncld(shoe_lsmeans, adjust = \"none\", Letters = LETTERS, decreasing = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n shoe        emmean   SE df lower.CL upper.CL .group\n Lightweight     69 1.41  3     64.5     73.5  A    \n Control         61 1.41  3     56.5     65.5   B   \n Stability       56 1.41  3     51.5     60.5   B   \n\nConfidence level used: 0.95 \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n:::\n  \n\n## Tukey’s Honestly Significant Difference (HSD) {.scrollable}\n\n- Designed specifically for *all* pairwise comparisons  \n- Controls family-wise error rate  \n\n::: callout\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nshoe_lsmeans <- emmeans(shoe_mod, specs = ~ shoe)\npairs(shoe_lsmeans, infer = c(TRUE, TRUE), adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate SE df lower.CL upper.CL t.ratio p.value\n Control - Lightweight         -8  2  3   -16.36    0.358  -4.000  0.0560\n Control - Stability            5  2  3    -3.36   13.358   2.500  0.1681\n Lightweight - Stability       13  2  3     4.64   21.358   6.500  0.0151\n\nConfidence level used: 0.95 \nConf-level adjustment: tukey method for comparing a family of 3 estimates \nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\ncld(shoe_lsmeans, adjust = \"tukey\", Letters = LETTERS, decreasing = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n shoe        emmean   SE df lower.CL upper.CL .group\n Lightweight     69 1.41  3     62.2     75.8  A    \n Control         61 1.41  3     54.2     67.8  AB   \n Stability       56 1.41  3     49.2     62.8   B   \n\nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 3 estimates \nP value adjustment: tukey method for comparing a family of 3 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n:::\n\n## Bonferroni Adjustment \n\nBonferroni controls error by:\n\n- Using a smaller significance level  \n\n$$\n\\alpha^* = \\frac{\\alpha}{\\text{number of tests}}\n$$\n\nSimple, but often conservative.\n\n\n## Dunnet's Test {.scrollable}\n \nUseful when interest lies in comparing all treatments to a control.\n\n::: callout\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nshoe_lsmeans <- emmeans(shoe_mod, specs = ~ shoe)\ncontrast(shoe_lsmeans, \n         method = \"trt.vs.ctrl\", # Treatment vs. control contrast\n         adjust = \"dunnet\", # Dunnett adjustment\n         infer = c(TRUE, TRUE),\n         ref = \"Control\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              estimate SE df lower.CL upper.CL t.ratio p.value\n Lightweight - Control        8  2  3   0.0241    15.98   4.000  0.0496\n Stability - Control         -5  2  3 -12.9759     2.98  -2.500  0.1511\n\nConfidence level used: 0.95 \nConf-level adjustment: dunnettx method for 2 estimates \nP value adjustment: dunnettx method for 2 tests \n```\n\n\n:::\n:::\n\n\n:::\n\n\n",
    "supporting": [
      "02.2-crd-contrasts_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}