{
  "hash": "2aac9100fb852ae92a8b26c0e060fc6e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 4: Factorial Treatment Structure\"\nsubtitle: \"Higher-Order Interactions and Analysis Strategy\"\nformat: \n  revealjs:\n    # theme: simple # other modern-ish options: dark, simple, solarized\n    theme: simple\n    slide-number: c/t \n    # chalkboard: true # lets you draw on top of slides (keyboard: c) or open a board (b)\n    width: 1200\n    height: 675\n    css: modern-slides.css\n    auto-stretch: false\n    html-math-method: mathjax\n# format: \n#   html:\n#     toc: true\n#   pdf:\n#     toc: false\nexecute: \n  warning: false\n  message: false\n  echo: false\n---\n\n## Example 4.4: Exercise Performance\n\n```{=html}\n<style>\n.reveal .slides .small table { font-size: 0.78em; line-height:1.05; }\n.reveal .slides .small table th, .reveal .slides .small table td { padding:6px 8px; }\n</style>\n```\n\nThe effects of warm-up type (no warm-up vs. dynamic stretching), pre-workout supplement (none vs. pre-workout drink), and music type (no music vs. upbeat music) on exercise tolerance were studied in a small-scale experiment involving 24 adults aged 25-35. Exercise tolerance was measured as the number of minutes until the subject reached fatigue while performing on a stationary bicycle. Each participant was randomly assigned to a warm-up type – pre-workout supplement – music type condition before completing the exercise tolerance stress test. The data can be found in [`04-stress_test.csv`](_data/04_stress_data.csv).\n\n## Example 4.4: The Data {.small}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Subject|Warmup             |Preworkout        |Music        | Tolerance|\n|-------:|:------------------|:-----------------|:------------|---------:|\n|       1|Dynamic stretching |Pre-workout drink |Upbeat music |      29.2|\n|       2|No warm-up         |Pre-workout drink |No music     |      14.8|\n|       3|Dynamic stretching |Pre-workout drink |Upbeat music |      24.1|\n|       4|No warm-up         |None              |No music     |       6.1|\n|       5|Dynamic stretching |None              |Upbeat music |      14.6|\n|       6|Dynamic stretching |Pre-workout drink |No music     |      17.6|\n\n\n:::\n:::\n\n\n## Study Blueprint\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](_images/046-stress-blueprint.png){width=80%}\n:::\n:::\n\n\n## Study Structure\n\n**Treatment Structure**\n\nA 2x2x2 full factorial between warm-up type (no warm-up vs. dynamic stretching), pre-workout supplement (none vs. pre-workout supplement), and music type (no music vs. upbeat music) for a total of t = 8 treatments.\n\n**Experimental Structure**\n\nWarm-up type, pre-workout supplement, and music type combinations are randomly assigned to subjects (e.u.) in a CRD with r = 3. The time until reaching fatigue on a stationary bicycle (seconds) is recorded for each subject (m.u.) for a total N = 24 subjects.\n\n## Adding a Third Factor (2x2x2)\n\nWith three factors -> t = 8 treatments\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](_images/046-stress-trt-structure.png){width=90%}\n:::\n:::\n\n\n-   main effects: Warm-up, Pre-workout, Music\n-   two-way interactions: Warm-up x Pre-workout, Warm-up x Music, Pre-workout x Music\n-   three-way interaction: Warm-up x Pre-workout x Music\n\n## What is a three-way interaction?\n\n+ <span style=\"font-size:0.8em\"> A three-way interaction exists when the way two factors interact depends on the level of a third factor. </span>\n+ <span style=\"font-size:0.8em\">AKA: a two-way interaction is not consistent across levels of a third factor. </span>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](04.3-higher-order-interactions_files/figure-revealjs/unnamed-chunk-4-1.png){width=60%}\n:::\n:::\n\n\n## 3-way Treatment Effects Model\n\n$$y_{ijkl}=\\mu+\\alpha_i+\\beta_j+\\gamma_k+\\alpha\\beta_{ij}+\\alpha\\gamma_{ik}+\\beta\\gamma_{jk}+\\alpha\\beta\\gamma_{ijk}+\\epsilon_{ijkl} \\text{ with } \\epsilon_{ijkl} \\text{ iid }\\sim N(0,\\sigma^2)$$ for $i=1,2; j=1,2; k=1,2; l=1,2,3$\n\nwhere... continued on next slide!\n\n## 3-way Treatment Effects Model\n\n<div style=\"font-size:0.7em\">\n\n-   $y_{ijkl}$: is the exercise tolerance (number of minutes until the subject reached fatigue) for the $l^{th}$ individual receiving the $i^{th}$ warm-up type, $j^{th}$ pre-workout supplement, and $k^{th}$ music type.\n-   $\\alpha_i$: the effect of the $i^{th}$ level of warm-up type.\n-   $\\beta_j$: the effect of the $j^{th}$ level of pre-workout supplement.\n-   $\\gamma_k$: the effect of the $k^{th}$ music type.\n-   $\\alpha\\beta_{ij}$: the interaction effect between the $i^{th}$ level of warm-up type and $j^{th}$ level of pre-workout supplement.\n-   $\\alpha\\gamma_{ik}$: the interaction effect between the $i^{th}$ level of warm-up type and $k^{th}$ level of music type.\n-   $\\beta\\gamma_{jk}$: the interaction effect between the $j^{th}$ level of pre-workout supplement and $k^{th}$ level of music type.\n-   $\\alpha\\beta\\gamma_{ijk}$: the interaction effect between the $i^{th}$ level of warm-up type, $j^{th}$ level of pre-workout supplement, and $k^{th}$ level of music type.\n-   $ϵ_{ijkl}$: the experimental error associated with the $l^{th}$ individual receiving the $i^{th}$ warm-up type, $j^{th}$ pre-workout supplement, and $k^{th}$ music type.\n\n</div>\n\n## 3-way ANOVA Table {.small}\n\n| SV      | DF              | SS    | MS = SS/DF | F         |\n|---------|-----------------|-------|------------|-----------|\n| A       | a-1             | SSA   | MSA        | MSA/MSE   |\n| B       | b-1             | SSB   | MSB        | MSB/MSE   |\n| C       | c-1             | SSC   | MSC        | MSC/MSE   |\n| AB      | (a-1)(b-1)      | SSAB  | MSAB       | MSAB/MSE  |\n| AC      | (a-1)(c-1)      | SSAC  | MSAC       | MSAC/MSE  |\n| BC      | (b-1)(c-1)      | SSBC  | MSBC       | MSBC/MSE  |\n| ABC     | (a-1)(b-1)(c-1) | SSABC | MSABC      | MSABC/MSE |\n| Error   | (r-1)(abc)      | SSE   | MSE        |           |\n| *Total* | N-1             |       |            |           |\n\n## Example 4.4: 3-way Skeleton ANOVA\n\n| Source of Variation  | DF  |\n|----------------------|-----|\n|                      |     |\n\n## R: Fit 3-way Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\n# same as Tolerance ~ Warmup + Preworkout + Music + Warmup:Preworkout + Warmup:Music + Preworkout:Music + Warmup:Preworkout:Music\nstress_mod <- lm(Tolerance ~ Warmup*Preworkout*Music, data = stress_data)\n```\n:::\n\n\n:::: columns\n::: column\nThis is your roadmap!\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Tolerance\n                        Df  Sum Sq Mean Sq F value    Pr(>F)    \nWarmup                   1 176.584 176.584 18.9155 0.0004971 ***\nPreworkout               1 242.570 242.570 25.9839 0.0001076 ***\nMusic                    1  70.384  70.384  7.5394 0.0143574 *  \nWarmup:Preworkout        1  13.650  13.650  1.4622 0.2441432    \nWarmup:Music             1  11.070  11.070  1.1859 0.2922989    \nPreworkout:Music         1  72.454  72.454  7.7612 0.0132205 *  \nWarmup:Preworkout:Music  1   1.870   1.870  0.2004 0.6604336    \nResiduals               16 149.367   9.335                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n::: column\nThese are your parameter estimates!\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Tolerance ~ Warmup * Preworkout * Music, data = stress_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-4.100 -1.842 -0.950  2.217  4.367 \n\nCoefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 16.2708     0.6237  26.088 1.54e-14 ***\nWarmup1                      2.7125     0.6237   4.349 0.000497 ***\nPreworkout1                 -3.1792     0.6237  -5.097 0.000108 ***\nMusic1                      -1.7125     0.6237  -2.746 0.014357 *  \nWarmup1:Preworkout1         -0.7542     0.6237  -1.209 0.244143    \nWarmup1:Music1               0.6792     0.6237   1.089 0.292299    \nPreworkout1:Music1           1.7375     0.6237   2.786 0.013221 *  \nWarmup1:Preworkout1:Music1   0.2792     0.6237   0.448 0.660434    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.055 on 16 degrees of freedom\nMultiple R-squared:  0.7976,\tAdjusted R-squared:  0.709 \nF-statistic: 9.007 on 7 and 16 DF,  p-value: 0.0001525\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## Check Model Assumptions: $\\epsilon_{ijkl} iid \\sim N(0, \\sigma^2)$\n\n\n::::: columns\n::: column\n\n::: {.cell code-folding='true'}\n\n```{.r .cell-code}\nstress_mod |> \n  broom::augment() |> \n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_hline(yintercept = 0,\n             color = \"#3a86d4\") +\n  labs(x = \"Fitted Values\", y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](04.3-higher-order-interactions_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell code-folding='true'}\n\n```{.r .cell-code}\nstress_mod |> \n  broom::augment() |> \n  ggpubr::ggqqplot(x = \".resid\",\n         color = \"#3a86d4\") +\n  labs(title = \"Normal QQ-Plot of Residuals\")\n```\n\n::: {.cell-output-display}\n![](04.3-higher-order-interactions_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n\n## 3-way Decision Flowchart\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](_images/046-three-way-decision-flowchart.png){width=386}\n:::\n:::\n\n\n## What are we testing with the F-tests?\n\n:::: columns\n::: column\n**3-way Interaction**\n\n$$\\scriptsize H_0:\\text{ All } \\alpha\\beta\\gamma_{ijk} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha\\beta\\gamma_{ijk} \\ne 0$$\n\n**2-way Interactions**\n\n$$\\scriptsize H_0:\\text{ All } \\alpha\\beta_{ij} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha\\beta_{ij} \\ne 0$$\n$$\\scriptsize H_0:\\text{ All } \\alpha\\gamma_{ik} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha\\gamma_{ik} \\ne 0$$\n$$\\scriptsize H_0:\\text{ All } \\beta\\gamma_{jk} = 0 \\text{  vs  } H_A: \\text{At least one } \\beta\\gamma_{jk} \\ne 0$$\n:::\n::: column\n**Main Effects**\n\n$$\\scriptsize H_0:\\text{ All } \\alpha_{i} = 0 \\text{  vs  } H_A: \\text{At least one } \\alpha_{i} \\ne 0$$\n$$\\scriptsize H_0:\\text{ All } \\beta_{j} = 0 \\text{  vs  } H_A: \\text{At least one } \\beta_{j} \\ne 0$$\n$$\\scriptsize H_0:\\text{ All } \\gamma_{k} = 0 \\text{  vs  } H_A: \\text{At least one } \\gamma_{k} \\ne 0$$\n:::\n::::\n\n## Let's go back to our ANOVA Table (i.e., Roadmap)\n\nWhat should we test first? Then what?\n\n:::: columns\n::: column\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Tolerance\n                        Df  Sum Sq Mean Sq F value    Pr(>F)    \nWarmup                   1 176.584 176.584 18.9155 0.0004971 ***\nPreworkout               1 242.570 242.570 25.9839 0.0001076 ***\nMusic                    1  70.384  70.384  7.5394 0.0143574 *  \nWarmup:Preworkout        1  13.650  13.650  1.4622 0.2441432    \nWarmup:Music             1  11.070  11.070  1.1859 0.2922989    \nPreworkout:Music         1  72.454  72.454  7.7612 0.0132205 *  \nWarmup:Preworkout:Music  1   1.870   1.870  0.2004 0.6604336    \nResiduals               16 149.367   9.335                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n::: {.cell-output .cell-output-error}\n\n```\nError in `knitr::include_graphics()`:\n! Cannot find the file(s): \"images/046-jmp-anova.png\"\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## What should we \"dig into\"?\n\n1. 3-way interaction:\n\n  + At an $\\alpha = 0.05$ we do not have enough evidence to conclude there is a significant 3-way interaction between warmup, preworkout, and music on the tolerance (F = 0.2; df = 1,16; p = 0.6604).\n\n## What should we \"dig into\"?\n\n2. 2-way interactions:\n\n  + **We have enough evidence to conclude there is a significant 2-way interaction between preworkout and music on the tolerance (F = 7.76; df = 1,16; p = 0.0132).**\n  + We do not have enough evidence to conclude there is a significant 2-way interaction between warmup and music on the tolerance (F = 1.19; df = 1,16; p = 0.2922).\n  + We do not have enough evidence to conclude there is a significant 2-way interaction between warmup and preworkout on the tolerance (F = 1.46; df = 1,16; p = 0.2441). \n  \n## What should we \"dig into\"?\n\n3. Main effects:\n\n  + Music.. don't care.\n  + Preworkout.. don't care\n  + **We have enough evidence to conclude there is a significant main effect of warmup on the tolerance (F = 18.91; df = 1,16; p = 0.0005).**\n  \n## What should we \"dig into\"?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](_images/046-three-way-decision-flowchart-stress.png){fig-align='center' width=40%}\n:::\n:::\n\n\n+ 2-way interaction between preworkout x music (averaged over warm-up)\n+ Main effect of warm-up (separately)\n  \n## R: 2-way Interaction Effect: Preworkout x Music\n\n*Averaged over workout levels: none/stretching*\n\n:::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\nlibrary(multcomp)\nemmip(stress_mod, Music ~ Preworkout, CIs = TRUE, adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.3-higher-order-interactions_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=70%}\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(stress_mod, specs = ~ Preworkout*Music) |> \n  cld(Letters = LETTERS, decreasing = T, adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Preworkout        Music        emmean   SE df lower.CL upper.CL .group\n Pre-workout drink Upbeat music   22.9 1.25 16    19.40     26.4  A    \n Pre-workout drink No music       16.0 1.25 16    12.50     19.5   B   \n None              No music       13.1 1.25 16     9.62     16.6   B   \n None              Upbeat music   13.1 1.25 16     9.57     16.6   B   \n\nResults are averaged over the levels of: Warmup \nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 4 estimates \nP value adjustment: tukey method for comparing a family of 4 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n:::\n::::\n\n## Pairwise Comparisons: Preworkout x Music (avg over Workout)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(stress_mod, specs = ~ Preworkout*Music) |>\n  pairs(adjust = \"tukey\", infer = c(T,T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                                        estimate   SE df lower.CL upper.CL t.ratio p.value\n None No music - (Pre-workout drink No music)                       -2.88 1.76 16    -7.93     2.16  -1.635  0.3883\n None No music - None Upbeat music                                   0.05 1.76 16    -5.00     5.10   0.028  1.0000\n None No music - (Pre-workout drink Upbeat music)                   -9.78 1.76 16   -14.83    -4.74  -5.546  0.0002\n (Pre-workout drink No music) - None Upbeat music                    2.93 1.76 16    -2.11     7.98   1.663  0.3740\n (Pre-workout drink No music) - (Pre-workout drink Upbeat music)    -6.90 1.76 16   -11.95    -1.85  -3.911  0.0061\n None Upbeat music - (Pre-workout drink Upbeat music)               -9.83 1.76 16   -14.88    -4.79  -5.574  0.0002\n\nResults are averaged over the levels of: Warmup \nConfidence level used: 0.95 \nConf-level adjustment: tukey method for comparing a family of 4 estimates \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n\n\n## R: Main effect of Warmup\n\n:::: columns\n::: column\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\nlibrary(multcomp)\nemmip(stress_mod, ~ Warmup, CIs = TRUE, adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.3-higher-order-interactions_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=70%}\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(stress_mod, specs = ~ Warmup) |> \n  cld(Letters = LETTERS, decreasing = T, adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Warmup             emmean    SE df lower.CL upper.CL .group\n Dynamic stretching   19.0 0.882 16     16.8     21.2  A    \n No warm-up           13.6 0.882 16     11.4     15.7   B   \n\nResults are averaged over the levels of: Preworkout, Music \nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 2 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(stress_mod, specs = ~ Warmup) |> \n  pairs(adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                          estimate   SE df t.ratio p.value\n Dynamic stretching - (No warm-up)     5.42 1.25 16   4.349  0.0005\n\nResults are averaged over the levels of: Preworkout, Music \n```\n\n\n:::\n:::\n\n:::\n::::\n\n## R: *What if* there had been a 3-way interaction?\n\n:::: columns\n::: {.column width=40%}\n\n::: {.cell}\n\n```{.r .cell-code}\nemmip(stress_mod, Preworkout ~ Music | Warmup, \n      CIs = TRUE, \n      adjust = \"tukey\")\n```\n\n::: {.cell-output-display}\n![](04.3-higher-order-interactions_files/figure-revealjs/unnamed-chunk-19-1.png){width=100%}\n:::\n:::\n\n:::\n::: {.column width=60%}\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(stress_mod, ~ Preworkout:Music:Warmup) |>\n  cld(Letters = LETTERS, decreasing = T, adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Preworkout        Music        Warmup             emmean   SE df lower.CL upper.CL .group\n Pre-workout drink Upbeat music Dynamic stretching   26.0 1.76 16    20.44     31.5  A    \n Pre-workout drink No music     Dynamic stretching   19.9 1.76 16    14.34     25.4  AB   \n Pre-workout drink Upbeat music No warm-up           19.8 1.76 16    14.30     25.4  AB   \n None              No music     Dynamic stretching   16.0 1.76 16    10.50     21.6   BC  \n None              Upbeat music Dynamic stretching   14.1 1.76 16     8.54     19.6   BC  \n Pre-workout drink No music     No warm-up           12.1 1.76 16     6.60     17.7   BC  \n None              Upbeat music No warm-up           12.1 1.76 16     6.54     17.6   BC  \n None              No music     No warm-up           10.2 1.76 16     4.67     15.7    C  \n\nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 8 estimates \nP value adjustment: tukey method for comparing a family of 8 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n:::\n::::",
    "supporting": [
      "04.3-higher-order-interactions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}