---
title: "Activity 4.2: Factorial Analysis"
subtitle: "Pig Feed Experiment"
execute: 
  error: true
  message: false
  warning: false

echo: false
format:
  docx: default
  html: default
  pdf: default
---
\vspace{-.8in}

::: callout-warning
- Submit via Gradescope, don't forget to assign pages to the questions in the outline!

- Delete any extraneous instructions (**like this box**) before submission. *You will be deducted points from now on if you do not follow this instruction!*

- Delete anything like `\vspace{}`

- Remember that it's okay if you cannot get the .qmd to render to submit this!! I will help you but you can also use any of the other formats.

- You should follow the qmd template for coding: [04.2-activity-analyze-factorials.qmd](../student/04.2-activity-analyze-factorials.qmd)

:::

A study was performed to investigate the effects of two feed additives on the growth of male pigs. The additives were Lysine (at 0%, 0.05%, 0.10% and 0.15% added to feed) and Soy Protein (12% or 14%). There were four pigs assigned at random to each treatment combination and each pig was randomly assigned to a separate pen in the building. The measured response was Average Daily Gain (ADG), in pounds, of each pig, over a 7-day period on the experimental feeds. The data are in the file `pigfeed_data.csv` found on Canvas.

::: callout-warning
Ensure `lysine` and `protein` are a character/factor data types after reading the data into R. By default it will read these in as numeric. Code is provided in the .qmd template to do this!
:::

The researchers would like to determine which of these additives, if any, affect the pigs’ weight gain, and what trends there are, if any, among the different levels of the additives. In addition, the researchers would like to know if there is a combination of lysine and soy protein which results in the most weight gain over the 7-day period.

## a. Identify the structure of the experiment

**Treatment structure**

\vspace{0.7in}

**Experimental structure**

\vspace{0.7in}

## b. Complete the skeleton ANOVA table below (delete rows you don't need)

| Source of Variation                  |DF        |
|--------------------------------------|----------|
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |

## c. State the statistical effects model

Make sure to define **all** terms, denote $i,j,k$ values, and include assumptions.

\vspace{2in}

## d. Fit the factorial model in R

-   Following the decision flow chart, provide conclusions for the *relevant* effects. Make sure to support your answer using (F = ; df = ; p = ).

\vspace{0.9in}

-   Based on your conclusion above, should you proceed by looking at (circle or only keep one):

**B. Joint / Simple Effects** Since there is evidence of an interaction.

## e. Visualizing the interaction

-   Create a plot that illustrates how Lysine (x-axis) modifies the effect of Soy Protein (separate colored lines) on ADG.
-   Copy/paste/sketch your plot (if you are not using this .qmd and integrating your plot directly.)
-   In 2–3 sentences, describe what you notice in the plot.

\vspace{2in}

## f. Simple effects: Protein within Lysine

Conduct slice tests to compare mean ADG between 12% and 14% Protein at each level of Lysine.

This aligns with the plot, which showed evidence of an effect of protein amount when lysine is 0 or .05, but not evidence of an effect of protein amount when lysine is .1 or .15 (the intervals overlap).

-   Lysine = 0: F = \_\_\_\_\_\_\_; df = \_\_\_\_\_, \_\_\_\_\_; p = \_\_\_\_\_\_\_\_

-   Lysine = 0.05: F = \_\_\_\_\_\_\_; df = \_\_\_\_\_, \_\_\_\_\_; p = \_\_\_\_\_\_\_\_

-   Lysine = 0.1: F = \_\_\_\_\_\_\_; df = \_\_\_\_\_, \_\_\_\_\_; p = \_\_\_\_\_\_\_\_

-   Lysine = 015: F = \_\_\_\_\_\_\_; df = \_\_\_\_\_, \_\_\_\_\_; p = \_\_\_\_\_\_\_\_

Summarize your findings in words, how does this support what you saw in the interaction plot above?

\vspace{0.8in}

## g. Recommendation

Which feed combination(s) would you recommend to maximize ADG, on average?

Support your recommendation with:

-   treatment means (with units),

-   and appropriate multiple comparisons (e.g., compact letter display).

```{r}
cld(pig_lsmeans, Letters = LETTERS, 
    decreasing = T, adjust = "tukey")
```
We recommend using 14% soy protein additive and either 0.05% or 0% lycine additive. The estimated mean ADG for male pigs fed 14% protein and 0.05% lycine was 3.12 pounds, which was not significantly different from that for male pigs fed 14% protein and 0% lycine of 3 pounds.

\vspace{1.5in}
