{
  "hash": "714ce9b9e817182812b538ae9b78efa1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Activity 2.2: Comparing Treatment Means\"\nsubtitle: \"Fruit Flies\"\nfilters:\n  - versions\nversions:\n  - instructions:\n      out-dir: \"..\"\n      yaml:\n        format:\n          html: \n            toc: true\n            html-table-processing: none\n          docx: default\n          pdf: default\n        echo: false\n  - student:\n      out-dir: \"..\"\n      yaml:\n        author: \"Your Name\"\n        format: typst\n        embed-resources: true\n        echo: true\n  - solution:\n      out-dir: \"..\"\n      out-file: \"02.2-activity-solution.qmd\"\n      yaml:\n        author: \"SOLUTIONS\"\n        html: \n            toc: true\n            html-table-processing: none\n        embed-resources: true\n        echo: true\nexecute: \n  error: true\n  message: false\n  warning: false\n---\n:::{.version-instructions}\n\n::: callout-note\nSubmit via Gradescope, don't forget to assign pages to the questions in the outline! Your submission will not be graded, if you don't assign pages.\n\nPlease delete any extraneous instructions (like this box) before submission.\n\nYou can also delete anything like `\\vspace{}`\n:::\n\n:::callout-note\n# Template .qmd + data\n\n- You should follow the template for coding: [02.2-activity-comparing-means.qmd](../student/02.2-activity-comparing-means.qmd)\n\n- The data are provided here in [`02_fruitfly_data.csv`](../_data/02_fruitfly_data.csv) and on Canvas.\n\n:::\n\n:::callout-warning\n# Sum to zero (effect coding) \n\nIn R, make sure to set your \"sum to zero\" constraint *before* fitting your model with `lm()`.\n\nI have included it in a chunk for you in the .qmd template (along with reading in data), make sure you have run that chunk before proceeding!\n\n:::\n\n:::\n\nScientists are interested in whether the energy costs of reproduction affect longevity in male fruit flies.\n\nIn this experiment:\n\n-   125 male fruit flies were randomly assigned to 5 treatment groups (25 flies per group).\n\n-   Males were housed individually.\n\n-   The treatments differed by the number and type of female companions provided per day:\n\n| Companion    | Description           |\n|--------------|-----------------------|\n| 1P (i = 1)   | One pregnant female   |\n| 8P (i = 2)   | Eight pregnant female |\n| 1V (i = 3)   | One virgin females    |\n| 8V (i = 4)   | Eight virgin female   |\n| None (i = 5) | No female companions  |\n\nThe response variable was longevity (days alive) for each male fruit fly.\n\n\n\n\n::: {.cell version='[\"student\",\"solution\"]'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(janitor)\nlibrary(emmeans)\nlibrary(multcomp)\n```\n:::\n\n\n\n::: {.cell version='[\"student\",\"solution\"]'}\n\n```{.r .cell-code}\n# set sum to zero option\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\n\n# read in data\n# YOU WILL NEED TO CHANGE THE FILE PATH BELOW\nfruitfly_data <- read_csv(\"../_data/02_fruitfly_data.csv\") |>\n  clean_names() |> \n  mutate(companions = factor(companions))\n\n# check levels\nlevels(fruitfly_data$companions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1 pregnant\" \"1 virgin\"   \"8 pregnant\" \"8 virgin\"   \"None\"      \n```\n\n\n:::\n:::\n\n\n## a. Skeleton ANOVA\n\nFill out the skeleton ANOVA according to the study.\n\n:::{.version-student .version-instructions}\n| Source of Variation (SV) | DF (total = \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_) |\n|--------------------------|-------------------------------------|\n|                          |                                     |\n|                          |                                     |\n:::\n\n:::{.version-solution}\n| Source of Variation (SV) | DF (total = 125-1 = 124) |\n|--------------------------|-------------------------------------|\n| Companion                |  (5-1) = 4                       |\n| MaleFly(Companion)       |   (25-1)(5)= 120                   |\n:::\n\n\n## b. Overall ANOVA F-test\n\nRun an ANOVA in R to assess whether any differences in mean longevity exist among the treatments. *Get in the habit of checking your model assumptions – residual vs fitted & qq-plots*.\n\n-   Complete the hypotheses using notation:\n\n:::{.version-student .version-instructions}\n    \n  -   $H_0:$\n\n  -   $H_A:$\n:::\n\n:::{.version-solution}\n    \n   $$H_0: \\mu_{1P} = \\mu_{8P}= \\mu_{1V} = \\mu_{8V} = \\mu_{None}$$\n\n  $$H_A: \\mbox{At least one }\\mu_i \\mbox{ is different}$$\n:::\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# R code for ANOVA here\n```\n:::\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# R code for testing assumptions here\n# - residual vs. fitted value plot + qqplot\n```\n:::\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nfly_mod <- lm(days ~ companions, data = fruitfly_data)\n\nanova(fly_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: days\n            Df Sum Sq Mean Sq F value    Pr(>F)    \ncompanions   4  11457 2864.27  11.917 3.472e-08 ***\nResiduals  120  28842  240.35                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\n# residual vs. fitted value plot\n\nfly_mod |> \n  broom::augment() |> \n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_hline(yintercept = 0,\n             color = \"#3a86d4\") +\n  labs(x = \"Fitted Values\", y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](02.2-activity-comparing-means_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# qqplot\n\nfly_mod |> \n  broom::augment() |> \n  ggpubr::ggqqplot(x = \".resid\",\n         color = \"#3a86d4\") +\n  labs(title = \"Normal QQ-Plot of Residuals\")\n```\n\n::: {.cell-output-display}\n![](02.2-activity-comparing-means_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n-   Write your conclusion in context including all evidence (F = ; df = ; p = ).\n\n:::{.version-instructions}\n\n\\vspace{0.6in}\n\n:::\n\n:::{.version-solution}\nNote: the assumptions appear to be met from our checks, so the p-value is valid.\n\nAt a significance level of $\\alpha = 0.05$, we have evidence to conclude that there is an effect of the type of the type of female fly companion on the longevity of male fruit flies, on average (F = 11.92, df = 4,120 , p <0.0001). In other words, we have evidence that the mean days alive for male fruit flies differs for at least one companion type.\n\nResults apply to male fruit flies similar to the ones in this study and under similar conditions.\n\n\n:::\n\n\n## c. Least Squares Means\n\nUse R to obtain the estimated mean longevity and standard error for each treatment and fill out the table below. \n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# lsms code\n```\n:::\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nfly_lsmeans <- emmeans(fly_mod, specs = ~ companions)\nfly_lsmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n companions emmean  SE  df lower.CL upper.CL\n 1 pregnant   63.6 3.1 120     57.4     69.7\n 1 virgin     64.8 3.1 120     58.7     70.9\n 8 pregnant   55.8 3.1 120     49.7     62.0\n 8 virgin     38.7 3.1 120     32.6     44.9\n None         61.4 3.1 120     55.2     67.5\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n:::{.version-instructions .version-student}\n| Companion | LSMean       | Standard Error |\n|-----------|--------------|----------------|\n| 1P        | $\\hat\\mu_1=$ |                |\n| 8P        | $\\hat\\mu_2=$ |                |\n| 1V        | $\\hat\\mu_3=$ |                |\n| 8V        | $\\hat\\mu_4=$ |                |\n| None      | $\\hat\\mu_5=$ |                |\n:::\n\nThen, create a plot of the least square means (look at it!).\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# plot code\n```\n:::\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\n# plot code\n\nemmip(fly_mod, ~ companions, CIs = T) +\n  labs(y = \"Estimated Days Alive\")\n```\n\n::: {.cell-output-display}\n![](02.2-activity-comparing-means_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## d. Interpret Estimated Means\n\nUsing the estimated parameters / coefficients (e.g., $\\hat \\mu$, $\\hat \\tau_1$, $\\hat{\\sigma}^2$), show by hand how $\\hat \\mu_1$ and $SE(\\hat \\mu_1)$ is obtained. Interpret these values in context of the problem.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nsummary(fly_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = days ~ companions, data = fruitfly_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-55.36  -8.80   1.64   9.16  32.44 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   56.856      1.387  41.002  < 2e-16 ***\ncompanions1    6.704      2.773   2.417  0.01714 *  \ncompanions2    7.944      2.773   2.864  0.00493 ** \ncompanions3   -1.016      2.773  -0.366  0.71475    \ncompanions4  -18.136      2.773  -6.539 1.58e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.5 on 120 degrees of freedom\nMultiple R-squared:  0.2843,\tAdjusted R-squared:  0.2604 \nF-statistic: 11.92 on 4 and 120 DF,  p-value: 3.472e-08\n```\n\n\n:::\n:::\n\n\n\n\n-   $\\hat \\mu_1=$\n\n:::{.version-instructions}\n    \\vspace{0.6in}\n:::\n\n:::{.version-solution}\n  $= \\mu +\\hat{\\tau}_1 = 56.856 +  6.704 = 63.56$\n:::\n\n-   $SE(\\hat\\mu_1)=$\n\n:::{.version-instructions}\n    \\vspace{0.6in}\n:::\n\n:::{.version-solution}\n  $= \\sqrt{\\frac{\\sigma^2}{r}} = \\sqrt{\\frac{240.35}{25}} \\approx 3.1$\n:::\n\n-   Interpretation:\n\n:::{.version-instructions}\n    \\vspace{0.6in}\n:::\n\n:::{.version-solution}\n\nThe estimated mean longevity in days for a male fruit fly with one pregnant female fly companion is around 63 days (s.e. = 3.1).\n:::\n\n## e. Planned Contrast 1: Any Females vs No Females\n\nScientists are interested in whether exposure to any females affects longevity.\n\n-   Write the Contrast:\n\n:::{.version-solution}\n$C = (\\frac{1}{4}, \\frac{1}{4}, \\frac{1}{4}, \\frac{1}{4}, -1)$\n:::\n\n-   Using R, carry out the test and provide the following in context of the problem:\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# code for test\n```\n:::\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\n# code for contrast test\ncontrast(fly_lsmeans,\n         method = list(\"Any Females vs. None\" = c(0.25, 0.25, 0.25, 0.25, -1)),\n         infer = c(TRUE, TRUE)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast             estimate   SE  df lower.CL upper.CL t.ratio p.value\n Any Females vs. None    -5.63 3.47 120    -12.5     1.23  -1.624  0.1070\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n    -   Interpret the estimated mean:\n\n:::{.version-instructions}\n        \\vspace{0.6in}\n:::\n\n:::{.version-solution}\n\nWe estimate that the mean longevity for male fruit flies with some type of female companion(s) is 5.63 days (s.e. = 3.5 days) shorter than the mean longevity for male fruit flies with no female companion.\n:::\n\n    -   Interpret the confidence interval:\n\n:::{.version-instructions}\n        \\vspace{0.6in}\n:::\n\n:::{.version-solution}\n\nWe are 95% confident that the population mean longevity (days) for male fruit flies with some type of female companion(s) is between 12.5 days shorter to 1.2 days longer than the average longevity of male fruit flies with no female companion.\n:::\n\n    -   Provide a conclusion for the test (include all evidence – t = , df = , p = ):\n\n:::{.version-instructions}\n        \\vspace{0.6in}\n:::\n\n:::{.version-solution}\n\nAt a $\\alpha = 0.05$ significance level, we do not have evidence that the mean longevity of male fruit flies with any type of female companion(s) is different from the mean longevity of male fruit flies with no female companion (t = -1.62; df = 120; p = 0.107) for flies similar to those in the study.\n:::\n\n## f. Pairwise Comparisons\n\nScientists also want to know which specific treatments differ from each other.\n\nPerform all pairwise comparisons using *no* adjustment (i.e., Fishers LSD) and *Tukey's* adjustment. Provide the p-value for each pairwise comparison in the table below.\n\n:::{.version-instructions}\n+----------------+----------+--------------------+-------------------+\n| Comparison\\    | Estimate | Unadjusted p-value | Adjusted p-value\\ |\n| (e.g. 1P - 1V) |          |                    | Tukey)            |\n+================+==========+====================+===================+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n|                |          |                    |                   |\n+----------------+----------+--------------------+-------------------+\n:::\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\npairs(fly_lsmeans, adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate   SE  df t.ratio p.value\n 1 pregnant - 1 virgin      -1.24 4.38 120  -0.283  0.7778\n 1 pregnant - 8 pregnant     7.72 4.38 120   1.761  0.0809\n 1 pregnant - 8 virgin      24.84 4.38 120   5.665 <0.0001\n 1 pregnant - None           2.20 4.38 120   0.502  0.6168\n 1 virgin - 8 pregnant       8.96 4.38 120   2.043  0.0432\n 1 virgin - 8 virgin        26.08 4.38 120   5.948 <0.0001\n 1 virgin - None             3.44 4.38 120   0.784  0.4343\n 8 pregnant - 8 virgin      17.12 4.38 120   3.904  0.0002\n 8 pregnant - None          -5.52 4.38 120  -1.259  0.2105\n 8 virgin - None           -22.64 4.38 120  -5.163 <0.0001\n```\n\n\n:::\n\n```{.r .cell-code}\npairs(fly_lsmeans, adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate   SE  df t.ratio p.value\n 1 pregnant - 1 virgin      -1.24 4.38 120  -0.283  0.9986\n 1 pregnant - 8 pregnant     7.72 4.38 120   1.761  0.4014\n 1 pregnant - 8 virgin      24.84 4.38 120   5.665 <0.0001\n 1 pregnant - None           2.20 4.38 120   0.502  0.9871\n 1 virgin - 8 pregnant       8.96 4.38 120   2.043  0.2520\n 1 virgin - 8 virgin        26.08 4.38 120   5.948 <0.0001\n 1 virgin - None             3.44 4.38 120   0.784  0.9347\n 8 pregnant - 8 virgin      17.12 4.38 120   3.904  0.0015\n 8 pregnant - None          -5.52 4.38 120  -1.259  0.7168\n 8 virgin - None           -22.64 4.38 120  -5.163 <0.0001\n\nP value adjustment: tukey method for comparing a family of 5 estimates \n```\n\n\n:::\n:::\n\n\n\n\n-   How do the *unadjusted* and *adjusted* p-values compare?\n\n:::{.version-instructions}\n    \\vspace{0.6in}\n:::\n\n:::{.version-solution}\nThe adjusted p-values are larger.\n:::\n\n## g. Tukey Letter Groupings\n\nUsing the *Tukey* pairwise comparisons in (f) and your table of estimated means in (c), fill out the compact letter display table below. *Note: you can check your answers in R.*\n\n:::{.version-instructions .version-student}\n| Companions | LSMean | Group |\n|------------|--------|-------|\n|            |        |       |\n|            |        |       |\n|            |        |       |\n|            |        |       |\n|            |        |       |\n|            |        |       |\n|            |        |       |\n|            |        |       |\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncld(fly_lsmeans, adjust = \"tukey\", \n    Letters = LETTERS, \n    decreasing = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n companions emmean  SE  df lower.CL upper.CL .group\n 1 virgin     64.8 3.1 120     56.7     72.9  A    \n 1 pregnant   63.6 3.1 120     55.5     71.7  A    \n None         61.4 3.1 120     53.3     69.5  A    \n 8 pregnant   55.8 3.1 120     47.7     63.9  A    \n 8 virgin     38.7 3.1 120     30.6     46.8   B   \n\nConfidence level used: 0.95 \nConf-level adjustment: sidak method for 5 estimates \nP value adjustment: tukey method for comparing a family of 5 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n\n\n:::\n:::\n\n\n\n## h. (Optional) Extra practice with contrasts\n\nIdentify the contrast coefficients for the following comparisons. Can you test these in R? How are they tested by hand?\n\n:::{.version-instructions .version-student}\n| Comparison                                | 1P  | 8P  | 1V  | 8V  | None |\n|-------------------------------------------|-----|-----|-----|-----|------|\n| Any Companion vs None                     |     |     |     |     |      |\n| Exposure to one female vs eight females   |     |     |     |     |      |\n| One virgin female vs eight virgin females |     |     |     |     |      |\n:::\n\n:::{.version-solution}\n| Comparison                                | 1P  | 8P  | 1V  | 8V  | None |\n|-------------------------------------------|-----|-----|-----|-----|------|\n| Any Companion vs None                     |  .25   |  .25   |  .25   |   .25  |   -1   |\n| Exposure to one female vs eight females   | .5    | -.5    | .5    |  -.5   |   0   |\n| One virgin female vs eight virgin females |   0  |  0   |   1  |  -1   |  0  |\n:::\n",
    "supporting": [
      "02.2-activity-comparing-means_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}