---
title: "1.1 Preparation: Syllabus and Intro to DOE"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📖 Read: 15 minutes

#### 📽 Watch Videos: 30-45 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Identify the factors, levels, treatments, and responses in a designed experiment.
- Identify experimental units, measurement units, and the role of subsampling in experimental design.
:::


## Syllabus

- 📖 Review Canvas and the [syllabus](../0-course-info/syllabus-f26.qmd).

- 📽 Watch at least the first 6 minutes of this introduction. The rest is if you would like a video walk-through of the syllabus!


{{< video https://youtu.be/D1y80v4FHrE >}}



## Basics of Design of Experiments (DOE)

- We will be using many preparation videos made by the indomitable [Dr. Emily Robinson](https://github.com/earobinson95)! I (Dr. C) will occasionally add/edit slides used in these videos and record short follow-ups.
- 📽 Follow along with the [slides](../2-slides/01.1-basics-of-doe.qmd).
  - Note: you can export the slides to a pdf for notetaking via the bottom left three horizontal stacked lines > Tools > PDF Export Mode > Print + Save as PDF

{{< video https://www.youtube.com/watch?v=R65yHRQIBlc >}}


