---
title: "1.2 Preparation: Controlling for Variability and R & RStudio"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📖 Read: 15 minutes

#### 📽 Watch Videos: 20 min
 
#### ✅  Complete Activity: 20 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Distinguish between treatment structure and design structure.
- Recognize and apply principles of randomization, blocking, and replication to reduce variability.
- Differentiate between designed experiments and observational studies, explaining the implications for cause and effect

:::

## Controlling for Variability

- 📽 Follow along with the [slides](../2-slides/01.2-controlling-for-variability.qmd).
    - Note: the last two slides are a little different from Dr. Robinson's video. The explanation is continued in the second video (with Dr. C).

{{< video https://www.youtube.com/watch?v=aDxl9b4f2Lo >}}


{{< video https://www.youtube.com/watch?v=vTgW0CZLACs >}}


## Get Started with Discord

- ✅ Follow the instructions to [Join the STAT 3540 Discord Server](../0-course-info/discord-instructions.qmd). Make sure that you complete all of the "Get Started" tasks you will be prompted to do once you are in!

## Getting Started with R and RStudio

We are going to use R and RStudio throughout this course. You may have used Posit Cloud in previous courses, but in this course we will all work with a *local* version of the software. 

By the start of week 2, you will need to have the latest versions R and RStudio installed and working on your computer! Come by office hours and reach out if you are having trouble.


::: callout-warning
# Cannot Install R or RStudio

If for any reason you cannot download R or RStudio onto your laptop, please let
me know as soon as possible so we can figure something out.
:::

### Set up R and RStudio for STAT 3540 / 5440

- ✅  Follow the instructions to [Install / Update R](../0-course-info/getting-started-r.qmd#sec-installr).
- ✅  Follow the instructions to [Install / Update RStudio](../0-course-info/getting-started-r.qmd#sec-installrstudio)
- ✅  Follow the instructions to  ensure [Quarto is installed](../0-course-info/getting-started-r.qmd#sec-quarto) 
- ✅  Follow the instructions to  [create an RStudio Project](../0-course-info/getting-started-r.qmd#sec-rproject) for this course

### Learn About / Refresh R 

If you have not taken STAT 331 / STAT 1810 or used R in previous courses, **please take some time to get yourself acquainted with our good friend R!**

I will give you all of the code that you need throughout the course, but it will help you be less overwhelmed if you take some time in these first weeks to watch videos and do some tutorials. Please come by office hours if you are overwhelmed and ask lots of questions on Discord!!

😎 Get started at [Introduction to R and RStudio](../0-course-info/getting-started-r.qmd#sec-intror)
