---
title: "2.1 Preparation: Completely Randomized Designs"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📽 Watch Videos: 45 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Identify and describe the treatment structure and design structure in a Completely Randomized Design.
- Write out and interpret the ANOVA table for a one-way treatment structure in a CRD, including sources of variation and degrees of freedom.
- Design and execute a Completely Randomized Experiment using R, including the randomization of treatments to experimental units.
- State the statistical model for a one-way treatment structure in a CRD, define its parameters in the context of a given study, and construct the corresponding design matrix.
:::


**Notes:**

- There is one slide deck to follow along with, but the links below go to the relevant starting point for each video.

- Dr. Robinson discusses how to do analysis in JMP, you can **skip these!** We will not use JMP in this class and you will notice I removed those slides.

- Take notes while you watch and summarize the main points for yourself!

- If you want more or a different modality, read Oehlert Ch 3.

## Designing a CRD

- 📽 Follow along with the [slides](../2-slides/02.1-crd-design-analysis-model.qmd).
- Note that there are a couple of changes to the slides from the video. See Dr. C's follow-up video for clarification.

{{< video https://www.youtube.com/watch?v=STK99inn1jY >}}

[[DR C FOLLOW-UP VIDEO COMING SOON]]

## Analyzing a CRD

- 📽 Follow along with the [slides](../2-slides/02.1-crd-design-analysis-model.qmd#/analyzing-a-crd-anova). 
- Skip JMP slide 16:53-17:38.

{{< video https://www.youtube.com/watch?v=Fi1YjAvSQLY >}}

## Statistical Model for CRD

- 📽 Follow along with the [slides](../2-slides/02.1-crd-design-analysis-model.qmd#/statistical-model-for-a-crd) until 15:45.

{{< video https://www.youtube.com/watch?v=r3AePcSjfR8 >}}
