---
title: "3.1 Preparation: Power"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📽 Watch Videos: 20 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Explain the concept of power and its role in detecting meaningful effects in a study.
- Describe how variability, sample size, and design choices influence the power of the F-test.
- Use software tools to compute power and determine required sample sizes for different experimental designs.
 

:::

- If you want more or a different modality, read [Oehlert Ch 7](_text/oehlert_ch7.pdf).

## Estimating Treatment Means

- 📽 Follow along with the [slides](../2-slides/03.1-power.qmd).
- Ignore the bit on JMP! You will notice that our slide about R looks a little different than Dr. Robinson's -- we hav to install the needed package in a special way.
- You can play around with [this nifty applet](https://smzr97-test0student-ear.shinyapps.io/power-explorer-323/) to calculate and visualize.

{{< video https://www.youtube.com/watch?v=ijZxpent9rs >}}


## R Tips

If you are struggling a bit with R so far, please watch this video!

{{< video https://www.youtube.com/watch?v=GAWBuyq5HIk >}}
 
