---
title: "4.1 Preparation: Factorials Part I -- Design and Contrasts"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📽 Watch Videos: 30 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Define factorial treatment structures, differentiate treatment and design structures, and determine the skeleton ANOVA table.
- Design a CRD using a factorial treatment structure using R and communicate the design
- Explain what a statistical interaction is in the context of a specific experiment and identify whether statistical interaction exists when given an interaction plot or table of treatment means.
 

:::

**Notes:**

- If you want more or a different modality, read Oehlert Ch 8-9. 
    - Warning: we jump a bit more around Ch 8-9 for Module 4... we have three whole class days on this topic, so just skip around to sections that align with the day's lecture videos and slides.
- There is **one slide deck** to follow along with, but the links below go to the relevant starting point for each video.
- Skip JMP discussions
- **Take notes** while you watch and summarize the main points for yourself!

## Why Factorials? Treatment vs. Design Structure

- 📽 Follow along with the [slides](../2-slides/04.1-factorials.qmd).
- I again added some additional slides on implementing this study design "by hand" in R. I will post a separate video explaining.

{{< video https://www.youtube.com/watch?v=OqSS0Qqc_dM >}}


## Factorial Contrasts: Main, Simple, and Interaction Effects

- 📽 Follow along with the [slides](../2-slides/04.1-factorials.qmd#/factorial-contrasts-main-simple-and-interaction-effects).

{{< video https://www.youtube.com/watch?v=GVBrrMQTW7Y >}}



 
