---
title: "4.1 Preparation: Factorials Part II -- Analysis and Interactions"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📽 Watch Videos: 45 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Explain what a statistical interaction is in the context of a specific experiment and identify whether statistical interaction exists when given an interaction plot or table of treatment means.
- Explain what main effects are and identify whether main effects exist when given an interaction plot or table of means
- Analyze a CRD using a factorial treatment structure using software and interpret the results and articulate conclusions.
 
:::

**Notes:**

- If you want more or a different modality, read Oehlert Ch 8-9. 
    - Warning: we jump a bit more around Ch 8-9 for Module 4... we have three whole class days on this topic, so just skip around to sections that align with the day's lecture videos and slides.
- There is **one slide deck** to follow along with, but the links below go to the relevant starting point for each video.
- Skip JMP discussions
- **Take notes** while you watch and summarize the main points for yourself!

## Analyzing a Factorial: Model, ANOVA, and Decision Flow

- 📽 Follow along with the [slides](../2-slides/04.2-analyzing-a-factorial.qmd).

{{< video https://www.youtube.com/watch?v=GeAm7GwOwLk >}}


## Example: No Interaction, interpret Main Effects

- 📽 Follow along with the [slides](../2-slides/04.2-analyzing-a-factorial.qmd#/example-no-interaction-interpret-main-effects).

{{< video  https://www.youtube.com/watch?v=mElCQ4OB8Xw >}}

## Example: Interaction Present, interpret Simple Effects

- 📽 Follow along with the [slides](../2-slides/04.2-analyzing-a-factorial.qmd#/example-interaction-present-interpret-simple-effects).

{{< video https://www.youtube.com/watch?v=2jfeZ8XoGPQ >}}


 
