---
title: "5.1 Preparation: Designing and Analyzing Randombized Completely Blocked Designs"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📽 Watch Videos: 30 min

------------------------------------------------------------------------

::: callout
## Learning Objectives
- Explain the purpose of blocking and when to use a RCBD.
- Design and implement a RCBD, including appropriate blocking variables.
- Compare the statistical models and ANOVA tables for CRD and RCBD.
- Analyze RCBD data using statistical software and interpret results.
- Evaluate the effectiveness of blocking in reducing experimental error.
:::

**Notes:**

- If you want more or a different modality, read Oehlert Ch 13.1-13.2. 
- There is **one slide deck** to follow along with, but the links below go to the relevant starting point for each video.
- Skip JMP discussions
- **Take notes** while you watch and summarize the main points for yourself!

## Designing a RCBD

- 📽 Follow along with the [slides](../2-slides/05.1-design-analyze-rcbd.qmd).

{{< video  https://youtu.be/5fpDQvuVtUA >}}




## Analyzing a RCBD

- 📽 Follow along with the [slides](../2-slides/05.1-design-analyze-rcbd.qmd#/analyzing-a-rcbd).
- **Note:** I changed the notation slightly so that we use $M$ as the number of blocks (Dr. R uses $r$) and index the block with $m$ (rather than $j$ as in the video).

{{< video  https://youtu.be/Bj6G8pi1_lU >}}



 
