---
title: "7.1 Preparation: Expanding Treatment & Design Structures"
number-sections: true
number-depth: 2
---

```{r}
#| include: false
#| label: packages-setup

library(tidyverse)
```

#### 📽 Watch Videos: 45 min

------------------------------------------------------------------------

::: callout
## Learning Objectives

- Differentiate between standard experimental designs and extended structures like generalized block designs and Latin squares.
- Recognize when and why generalized block designs are needed to account for systematic differences.
- Understand how Latin square designs control for two blocking factors and when they are appropriate.
- Apply appropriate statistical models to analyze data from these expanded design structures.
:::

**Notes:**

- Skip JMP discussions
- There is **one slide deck** to follow along with, but the links below go to the relevant starting point for each video.
  - Some of the notation in our slides is different from Dr. Robinson to be **consistent** with our discussions throughout class **this semester**.
- **Take notes** while you watch and summarize the main points for yourself!
  - This includes breaking down R code to make sure you understand it!
- Data to follow along:
  - [07-cholesterol.csv](../2-slides/_data/07-cholesterol.csv)
  - [07-green_roof_data.csv](../2-slides/_data/07-green_roof_data.csv)


## Generalized Block Designs

- 📽 Follow along with the [slides](../2-slides/07.1-more-designs.qmd).

{{< video  https://www.youtube.com/watch?v=GAWmkKGzNp0 >}}



## Latin Square Design

- 📽 Follow along with the [slides](../2-slides/07.1-more-designs.qmd#/latin-square-design).

{{< video https://www.youtube.com/watch?v=5frP6pozvr0 >}}




 
