{
  "hash": "777a0863604feb07fd6afc166f56293e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Activity 1.1: Design Blueprints\"\nsubtitle: \"Turkeys in Pens\"\nfilters:\n  - versions\nversions:\n  - instructions:\n      out-dir: \"..\"\n      yaml:\n        eval: false\n        format:\n          html: default\n          docx: default\n  - student:\n      out-dir: \"..\"\n      yaml:\n        author: \"Your Name\"\n        format: typst\n  - solution:\n      out-dir: \"..\"\n      out-file: \"01.1-activity-solution.qmd\"\n      yaml:\n        author: \"SOLUTIONS\"\n        format: html\n        embed-resources: true\nexecute: \n  error: true\n  echo: true\n  message: false\n  warning: false\n---\n\n:::{.version-instructions}\n\n## 0. Software. \n\nWe will be using R and Rstudio in this course. To keep things simple for this first day, you can use [PositCloud](https://posit.cloud/content/12747010) if you do not have R and RStudio set up already for a different Class. \n\nIf you have R and Rstudio on your computer, you can download and use this template qmd: [01.1-activity-turkey-in-pens.qmd](../student/01.1-activity-turkey-in-pens.qmd)\n\nAlternatively, for **this activity only** you can use any software that you like to generate the plots and conduct the analysis. In this case, I would recommend downloading the Word version of this (under \"Other Formats\" the the right!) and filling it out in Word (or Google Docs).\n\n:::\n\n\n\n::: {.cell version='[\"student\",\"solution\"]'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\n```\n:::\n\n\n\n## Scenario\n\nWe are interested in examining the effect of dietary protein on growth in Standard Bronze farm-raised turkeys. There are 24 turkeys available for the study.\n\nThe turkeys are housed 3 to a pen, and each pen has a single feed trough, meaning all turkeys within a pen receive the same diet.\n\nTwo diets are studied:\n\n- Low-protein diet: 15% protein  \n- High-protein diet: 30% protein  \n\nDiets are assigned at random to pens, with 4 pens receiving each diet (8 pens total).\n\nThe turkeys are fed their assigned diet for 6 weeks. The primary outcome measured on each turkey is average daily weight gain (ADG), in lbs/day.\n\n## 1. Sketch a blueprint for this study.\n\n:::{.version-instructions}\n\\vspace{1.5in}\n:::\n\n:::{.version-student}\n*Include an image of your blueprint here*\n:::\n\n:::{.version-solution}\n![Design Blueprint](../_images/1.1-turkey_blueprint.png)\n:::\n\nNotes:\n\n- The study description **did not** indicate any grouping of the pens!\n- This is an example of **subsampling**\n\n## 2. Describe the study structure\n\n- **Treatment structure:**  \n\n:::{.version-instructions}\n\\vspace{0.5in}\n:::\n\n:::{.version-solution}\n    - Name: One-way\n    - Factor: Diet\n    - Levels: Low (15%) and High (30%)\n    - t = 2\n:::\n\n- **Design structure:**  \n\n:::{.version-instructions}\n\\vspace{0.5in}\n:::\n\n:::{.version-solution}\n    - Randomization: CRD\n    - e.u.: one pen\n      - r = 4\n      - n = 8\n    - m.u.: one turkey\n      - N = 24\n:::\n\n\n## 3. Pen-Level Data\n\na. Open the file `turkey_pen_data.csv`.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\npen_dat <- read_csv(\"../_data/01_turkey_pen_data.csv\")\n```\n:::\n\n\nNote: I have a slightly more complicated folder structure than you should so my **file path** is a bit more complicated! Look up \"relative file path\" for more information.\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# read in pen data\n\npen_dat <- read_csv(\"FILE PATH\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! 'FILE PATH' does not exist in current working directory:\n  '/Users/czmann/Documents/teaching/stat3540/3-activities/main-version'.\n```\n\n\n:::\n:::\n\n\nb. What does each row in this data file represent?\n\n:::{.version-solution}\n\n*One pen*\n:::\n\nc. How many observations are there per diet? Why?\n\n:::{.version-solution}\n\n*4 per diet since r = 4*\n:::\n\nd. Create a plot of pen-level ADG on the y-axis and Diet on the x-axis (Hint: each diet should have 4 dots). Don't forget to make sure your plot has clear axis labels and a title!\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nggplot(pen_dat) +\n  geom_point(aes(x = Diet,\n                 y = Pen_ADG)) +\n  labs(title = \"Pen-Level ADG by Diet\",\n       y = \"Average Pen ADG\")\n```\n\n::: {.cell-output-display}\n![](01.1-activity-turkey-in-pens_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# plot code \n# hint: think about what kind of plot makes sense and\n# then look up how to make that with ggplot\n```\n:::\n\n\n\n\ne. Create a summary table showing the mean and standard deviation of pen-level ADG for each diet.\n\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\npen_dat |> \n  group_by(Diet) |> \n  summarize(mean_pen_adg = mean(Pen_ADG),\n            sd_pen_adg = sd(Pen_ADG)) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Diet       | mean_pen_adg| sd_pen_adg|\n|:----------|------------:|----------:|\n|15% (low)  |        1.415|      0.304|\n|30% (high) |        1.315|      0.271|\n\n\n:::\n:::\n\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# table code\n```\n:::\n\n\n:::{.version-student}\nYou can delete the blank table below if you just want to output your result with reasonable column names. Or you can fill in the numbers.\n:::\n\n:::{.version-student .version-instructions}\n| Diet | Mean pen ADG | SD pen ADG |\n|------|--------------|------------|\n| Low (15%) | | |\n| High (30%) | | |\n:::\n\n## 4. Animal-Level Data\n\nf. Open the file `turkey_animal_data.csv`.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nanimal_dat <- read_csv(\"../_data/01_turkey_animal_data.csv\")\n```\n:::\n\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# read in animal data\n\nanimal_dat <- read_csv(\"FILE PATH\")\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! 'FILE PATH' does not exist in current working directory:\n  '/Users/czmann/Documents/teaching/stat3540/3-activities/main-version'.\n```\n\n\n:::\n:::\n\n\ng. What does each row in this data file represent? How many rows are there? Why?\n\n:::{.version-solution}\n*Each row represents one turkey, therefore there are 24 rows, one for each turkey*\n\n:::\n\nh. Create a plot of animal-level ADG on the y-axis and Diet on the x-axis.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nggplot(animal_dat) +\n  geom_jitter(aes(x = Diet,\n                 y = ADG),\n              height = 0,\n              width = .1,\n              alpha = .8)\n```\n\n::: {.cell-output-display}\n![](01.1-activity-turkey-in-pens_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n:::{.version-solution}\n*Note that some of the turkeys have the same ADG level, so if you just used `geom_point()`, you wouldn't see all 24 points. `geom_jitter()` adds some random noise to the points and `alpha` impacts the transparency.*\n\n:::\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# plot code \n# hint: think about what kind of plot makes sense and\n# then look up how to make that with ggplot\n```\n:::\n\n\ni. How many measurement/sampling units are there per diet in this plot?\n\n:::{.version-solution}\n*12 (if you did not use jitter, you might only see 7 per diet).*\n:::\n\n\nj. Create a summary table showing the mean and standard deviation of ADG for each diet.\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nanimal_dat |> \n  group_by(Diet) |> \n  summarize(mean_adg = mean(ADG),\n            sd_adg = sd(ADG)) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Diet       | mean_adg| sd_adg|\n|:----------|--------:|------:|\n|15% (low)  |    1.408|  0.297|\n|30% (high) |    1.308|  0.271|\n\n\n:::\n:::\n\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# table code\n```\n:::\n\n\n:::{.version-student}\nYou can delete the blank table below if you just want to output your result with reasonable column names. Or you can fill in the numbers.\n:::\n\n:::{.version-student .version-instructions}\n| Diet | Mean pen ADG | SD pen ADG |\n|------|--------------|------------|\n| Low (15%) | | |\n| High (30%) | | |\n:::\n\nk. Compare the animal-level means and standard deviations to the pen-level results. What do you notice?\n\n:::{.version-solution}\n*The means and stardard deviations are somewhat similar. The difference in the means between the two groups is the same!*\n:::\n\n## 5. Comparing Analyses\n\nNow consider a two-sample t-test comparing the low-protein and high-protein diets.\n\n### Pen-level analysis\n\nl. Using `turkey_pen_data.csv`, conduct a two-sample independent t-test (assume unequal variances).\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\n# saving the t.test object like this helps us get more results\npen_test <- t.test(Pen_ADG ~ Diet, data = pen_dat)\npen_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Pen_ADG by Diet\nt = 0.49128, df = 5.9222, p-value = 0.6409\nalternative hypothesis: true difference in means between group 15% (low) and group 30% (high) is not equal to 0\n95 percent confidence interval:\n -0.3996644  0.5996644\nsample estimates:\n mean in group 15% (low) mean in group 30% (high) \n                   1.415                    1.315 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\n# extract standard error from results\npen_test$stderr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2035518\n```\n\n\n:::\n:::\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# t-test code\n```\n:::\n\n\n:::{.version-instructions .version-student}\nReport:\n\n- Difference in mean ADG  \n- Standard error  \n- t-statistic, degrees of freedom, and p-value  \n:::\n\n\n:::{.version-solution}\n- Difference (Low - High) = .1 lbs\n- Standard error: 0.204 lbs\n- t = 0.49, df = 5.9, p-value = 0.64\n:::\n\n### Animal-level analysis\n\nm. Using `turkey_animal_data.csv`, conduct the same two-sample independent t-test (assume unequal variances).\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nanimal_test <- t.test(ADG ~ Diet, data = animal_dat)\nanimal_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  ADG by Diet\nt = 0.86155, df = 21.823, p-value = 0.3983\nalternative hypothesis: true difference in means between group 15% (low) and group 30% (high) is not equal to 0\n95 percent confidence interval:\n -0.1408273  0.3408273\nsample estimates:\n mean in group 15% (low) mean in group 30% (high) \n                1.408333                 1.308333 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell version='solution'}\n\n```{.r .cell-code}\nanimal_test$stderr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1160699\n```\n\n\n:::\n:::\n\n\n\n::: {.cell version='student'}\n\n```{.r .cell-code}\n# t-test code\n```\n:::\n\n\n\n:::{.version-instructions .version-student}\nReport:\n\n- Difference in mean ADG  \n- Standard error  \n- t-statistic, degrees of freedom, and p-value  \n:::\n\n\n:::{.version-solution}\n- Difference (Low - High) = .1 lbs\n- Standard error: 0.116 lbs\n- t = 0.86, df = 21.8, p-value = 0.40\n:::\n\n## 6. Interpretation\n\nn. Which analysis is *correct* for answering the research question? Explain.\n\n:::{.version-instructions .version-student}\nYour explanation should address:\n\n- What the experimental unit is  \n- Why one analysis artificially inflates the sample size  \n- Why this matters for statistical inference\n:::\n\n\n:::{.version-solution}\n*The correct analysis is the pen-level analysis. The experimental unit is a pen, and we should analyse the experiment at the experimental unit level. This is an example of sub-sampling! The turkey is the measurement unit, and there are multiple per experimental unit. Treating the turkey as the unit of analysis artificially inflates the sample size, and our estimates for the standard error and p-value are therefore too small.*\n:::\n\n\n:::{.version-instructions .version-student}\n## 7. Submit on Gradescope\n\nWhen you are finished, submit your work to **Gradescope**:\n\n1. Make sure your submission includes:\n\n   - Your study blueprint sketch\n   - Your written answers for parts (b)–(n)\n   - Any requested tables/values from R\n   \n2. Combine everything into **one PDF**.\n\n   - If you wrote on paper: take clear photos and save/print to PDF.\n   - If you typed responses: export to PDF.\n   - If you used Quarto: render your report (it is set to render as PDF).\n   \n3. Go to **Canvas > Gradescope > Activity 1.1: Design Blueprints** and upload your PDF.\n\n4. If Gradescope asks you to assign pages to questions, do so before submitting.\n:::",
    "supporting": [
      "01.1-activity-turkey-in-pens_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}