{
  "hash": "a20b0d843ec08dcfa0076a1aa74dd44f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 5: Randomized Complete Block Designs (RCBD)\"\nsubtitle: \"Factorial Treatment Design in a RCBD\"\nformat: \n  revealjs:\n    # theme: simple # other modern-ish options: dark, simple, solarized\n    theme: simple\n    slide-number: c/t \n    # chalkboard: true # lets you draw on top of slides (keyboard: c) or open a board (b)\n    width: 1200\n    height: 675\n    css: modern-slides.css\n    auto-stretch: false\n    html-math-method: mathjax\nexecute: \n  warning: false\n  message: false\n  echo: false\n---\n\n## Example 5.2: Dental\n\n```{=html}\n<style>\n.reveal .slides .small table { font-size: 0.78em; line-height:1.05; }\n.reveal .slides .small table th, .reveal .slides .small table td { padding:6px 8px; }\n</style>\n```\n\n\n::: {style=\"font-size:0.75em\"}\n> An anesthesiologist made a comparative study of the effects of acupuncture and codeine on postoperative dental pain in male subjects. The four treatment combinations were as follows:\n>\n> -   Placebo treatment (a sugar pill and two inactive acupuncture points)\n> -   Codeine treatment (a codeine pill and two inactive acupuncture points)\n> -   Acupuncture only (a sugar pill and two active acupuncture points)\n> -   Codeine and acupuncture (a codeine pill and two active acupuncture points)\n\n> Thirty-two subjects were grouped into 8 blocks of size 4 according to an initial evaluation of their pain tolerance. The subjects in each block were then randomly assigned to the four treatment combinations. The pain relief scores were obtained for all subjects two hours after dental treatment (data were collected on a double-blind basis). The higher the pain relief score the more effective the treatment.\n:::\n\n## Example 5.2 Blueprint\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](_images/053-dental-blueprint.png)\n:::\n:::\n\n\n2.  Why do you think *pain tolerance* was used as a blocking variable?\n\n## Example 5.2: Study Structure\n\n**Treatment Structure**\n\nA 2x2 full factorial between Drug (sugar/codeine) and Acupuncture (active/inactive) for a total of t = 4 treatment combinations.\n\n**Experimental Structure**\n\nDrug and acupuncture treatment combinations were randomly assigned to subjects (e.u.) in a RCBD with M = 8 replications (blocks) where pain tolerance is the blocking factor (block size = t = 4). We measured the pain releif scores on each subject (m.u.) for a total N = 32 subjects.\n\n## Statistical Effects Model\n\n::: {style=\"font-size:0.75em\"}\n$$y_{ijm} = \\mu + \\alpha_i + \\beta_j + \\alpha\\beta_{ij} + \\rho_m + \\epsilon_{ijm} \\text{ with } \\epsilon_{ijm} \\text{iid} \\sim N(0,\\sigma^2)$$ for $i = 1, 2; j = 1, 2; m = 1, 2, ..., 8$\n\nWhere:\n\n-   $y_{ijm}$ is the pain relief score from the subject in the $m^{th}$ pain tolerance block receiving the $i^{th}$ level of drug and the $j^{th}$ level acupuncture\n-   $\\mu$ is the overall mean pain relief score\n-   $\\alpha_i$ is the effect of the $i^{th}$ level of drug\n-   $\\beta_j$ is the effect of the $j^{th}$ level of acupuncture\n-   $\\alpha\\beta_{ij}$ is the interaction effect between the $i^{th}$level of drug and the $j^{th}$ level of acupuncture\n-   $\\rho_m$ is the effect of the $m^{th}$ block\n-   $\\epsilon_{ijk}$ is the experimental error associated with the subject from the $m^{th}$ block receiving the $i^{th}$ level of drug and the $j^{th}$ level of acupuncture\n:::\n\n## ANOVA Table\n\n| Source of Variation            | DF          | SS    | MS    | F         |\n|--------------------------------|-------------|-------|-------|-----------|\n| Blocks                         | M-1         | SSBlk | MSBlk | MSBlk/MSE |\n| A                              | a-1         | SSA   | MSA   | MSA/MSE   |\n| B                              | b-1         | SSB   | MSB   | MSB/MSE   |\n| AxB                            | (a-1)(b-1)  | SSAB  | MSAB  | MSAB/MSE  |\n| Block x AB $\\rightarrow$ error | (M-1)(ab-1) | SSE   | **MSE**   |           |\n| Total (N = Mab)                | N-1         |       |       |           |\n\n## Skeleton ANOVA\n\n| Source of Variation | DF  |\n|---------------------|-----|\n|                     |     |\n\n## Example 5.2: The Data\n\n::: callout-warning\nEnsure \"block\" is a factor/character!\n:::\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndental_data <- read_csv(\"_data/05-dental_data.csv\") |> \n  mutate(pain_tol = factor(pain_tol))\n\nhead(dental_data, n = 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  pain_tol drug    acupuncture score\n  <fct>    <chr>   <chr>       <dbl>\n1 1        sugar   active        0.6\n2 1        codeine inactive      0.5\n3 1        sugar   inactive      0  \n4 1        codeine active        1.2\n5 2        codeine inactive      0.6\n6 2        sugar   active        0.7\n7 2        sugar   inactive      0.3\n8 2        codeine active        1.3\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(dental_data$pain_tol) # since pain_tol is factor, ths will work and show the order of the levels\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1\" \"2\" \"3\" \"4\" \"5\" \"6\" \"7\" \"8\"\n```\n\n\n:::\n:::\n\n\n\n## R: Analysis -- fit model\n\nFit model (don't forget sum to zero contraints!):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set sum to zero constraint\noptions(contrasts = c(\"contr.sum\", \"contr.poly\"))\n\n# \"fit\" model -- saving model object to use in all of the rest of our analyses!\ndental_mod <- lm(score ~ drug + acupuncture + drug:acupuncture + pain_tol, \n                 data = dental_data)\n```\n:::\n\n\n:::callout-note\n# R model formulas and `lm` objects\n\nThe way we fit models in R using `lm` is by providing data + an *R formula*. R formulas are great because they *mirror* the statistical effects model that we write out mathematically for linear models! e.g. for our **two factor blocked model, the general formula** looks like:\n\n`response_var ~ factorA + factorB + factorA:factorB + block`\n\nThat looks just like the statistical effects model! \n\nWe could also use the shorthand formula:\n`response_var ~ factorA*factorB  + block`\n\n`delta_mod` is what we call a *model object* in R. All of the other functions that we use to do follow up analyses use this special kind of object -- nice!\n:::\n\n## R: Analysis -- ANOVA table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(dental_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: score\n                 Df Sum Sq Mean Sq  F value    Pr(>F)    \ndrug              1 2.3112  2.3112 159.7901 2.773e-11 ***\nacupuncture       1 3.3800  3.3800 233.6790 7.465e-13 ***\npain_tol          7 5.5988  0.7998  55.2963 4.126e-12 ***\ndrug:acupuncture  1 0.0450  0.0450   3.1111    0.0923 .  \nResiduals        21 0.3038  0.0145                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::callout-note\n# SST?\n\nR does not output the Total row of the ANOVA table, because it can be easily calculated by hand based on the other rows! It also does not go into the inference calculations for ANOVA itself.\n\n:::\n\n\n## R: Analysis -- parameter estimates\n\n:::callout-note\n# Estimated model\n\n$$\\hat{y}_{ijm} = \\hat{\\mu} + \\hat{\\alpha}_i + \\hat{\\beta}_j + \\hat{\\alpha\\beta}_{ij} + \\hat{\\rho}_m $$ \n\nWe get all of these estimated parameters from the estimated coefficient output using `summary(mod_obj)`\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dental_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = score ~ drug + acupuncture + drug:acupuncture + \n    pain_tol, data = dental_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.18125 -0.06250  0.00000  0.04688  0.24375 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         1.15625    0.02126  54.385  < 2e-16 ***\ndrug1               0.26875    0.02126  12.641 2.77e-11 ***\nacupuncture1        0.32500    0.02126  15.287 7.47e-13 ***\npain_tol1          -0.58125    0.05625 -10.333 1.09e-09 ***\npain_tol2          -0.43125    0.05625  -7.667 1.62e-07 ***\npain_tol3          -0.25625    0.05625  -4.556 0.000172 ***\npain_tol4          -0.28125    0.05625  -5.000 5.99e-05 ***\npain_tol5           0.09375    0.05625   1.667 0.110427    \npain_tol6           0.39375    0.05625   7.000 6.53e-07 ***\npain_tol7           0.49375    0.05625   8.778 1.80e-08 ***\ndrug1:acupuncture1  0.03750    0.02126   1.764 0.092304 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1203 on 21 degrees of freedom\nMultiple R-squared:  0.9739,\tAdjusted R-squared:  0.9615 \nF-statistic: 78.37 on 10 and 21 DF,  p-value: 2.521e-14\n```\n\n\n:::\n:::\n\n\n\n\n\n## Check Model Assumptions $\\epsilon_{ijm} \\text{iid} \\sim N(0\\sigma^2)$\n\n:::callout-note\n# Still just need our `mod_obj!`\n\nNote that all you need to change in this code (as always) is the model object (in this example, `delta_mod`). How useful!\n\n:::\n\n\n::::: columns\n::: column\n\n::: {.cell code-folding='true'}\n\n```{.r .cell-code}\ndental_mod |> \n  broom::augment() |> \n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point() +\n  geom_hline(yintercept = 0,\n             color = \"#3a86d4\") +\n  labs(x = \"Fitted Values\", y = \"Residuals\")\n```\n\n::: {.cell-output-display}\n![](05.2-factorial-in-rcbd_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell code-folding='true'}\n\n```{.r .cell-code}\ndental_mod |> \n  broom::augment() |> \n  ggpubr::ggqqplot(x = \".resid\",\n         color = \"#3a86d4\") +\n  labs(title = \"Normal QQ-Plot of Residuals\")\n```\n\n::: {.cell-output-display}\n![](05.2-factorial-in-rcbd_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n\n## Factorial flow chart\n\n> Where should we proceed with our analysis?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(dental_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: score\n                 Df Sum Sq Mean Sq  F value    Pr(>F)    \ndrug              1 2.3112  2.3112 159.7901 2.773e-11 ***\nacupuncture       1 3.3800  3.3800 233.6790 7.465e-13 ***\npain_tol          7 5.5988  0.7998  55.2963 4.126e-12 ***\ndrug:acupuncture  1 0.0450  0.0450   3.1111    0.0923 .  \nResiduals        21 0.3038  0.0145                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n## Main Effect of Drug\n\n\n:::columns\n:::{.column width=70%}\n\n::: {.cell}\n\n```{.r .cell-code}\ndental_drug_lsmeans <- emmeans(dental_mod, ~ drug)\nemmip(dental_mod, ~ drug, CIs = T)\n```\n\n::: {.cell-output-display}\n![](05.2-factorial-in-rcbd_files/figure-revealjs/unnamed-chunk-9-1.png){width=384}\n:::\n\n```{.r .cell-code}\ndental_drug_lsmeans |> \n  pairs(infer = c(T,T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast        estimate     SE df lower.CL upper.CL t.ratio p.value\n codeine - sugar    0.537 0.0425 21    0.449    0.626  12.641 <0.0001\n\nResults are averaged over the levels of: acupuncture, pain_tol \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n\n:::{.column width=30%}\n\n\n::: {style=\"font-size:0.75em\"}\n\n:::callout-note\n# R note\n\nFor theses follow-up analyses we need functions from the **emmeans** package.\n\nThe first step is creating an `lsmeans` object using the `emmeans()` function and our `mod_obj` object!\n\n:::\n\n\n> Codeine results in the highest mean pain relief at 1.42 (s.e. 0.03). This is, on average, 0.53 points more relief than the sugar pill (t = 12.64; df = 21; p \\< 0.0001).\n:::\n:::\n:::\n\n## Main Effect of Acupuncture\n\n:::columns\n:::{.column width=70%}\n\n::: {.cell}\n\n```{.r .cell-code}\ndental_acu_lsmeans <- emmeans(dental_mod, ~ acupuncture)\nemmip(dental_mod, ~ acupuncture, CIs = T)\n```\n\n::: {.cell-output-display}\n![](05.2-factorial-in-rcbd_files/figure-revealjs/unnamed-chunk-10-1.png){width=384}\n:::\n\n```{.r .cell-code}\ndental_acu_lsmeans |> \n  pairs(infer = c(T,T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate     SE df lower.CL upper.CL t.ratio p.value\n active - inactive     0.65 0.0425 21    0.562    0.738  15.287 <0.0001\n\nResults are averaged over the levels of: drug, pain_tol \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n:::\n\n:::{.column width=30%}\n::: {style=\"font-size:0.75em\"}\n> Active acupuncture results in the highest mean pain releif at 1.48 (s.e. = 0.03). This is, on average, 0.65 points higher than inactive acupuncture (t = 15.29; df = 21; p \\< 0.0001).\n:::\n:::\n:::\n\n\n",
    "supporting": [
      "05.2-factorial-in-rcbd_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}