---
title: "Activity 5.2: Analyzing Blocked Designs"
subtitle: "Cheese"
execute: 
  error: true
  message: false
  warning: false

author: Your Name
echo: true
embed-resources: true
format: typst
---
```{r}
#| echo: false

library(edibble)
library(tidyverse)
library(emmeans)
library(multcomp)
```

# Scenario

An experiment is to be conducted to evaluate the effect of citric acid and salt on the moisture content (in %) of [mozzarella cheese](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/mozzarella-cheese). Typically, mozzarella cheese has a moisture content between 52 and 60%, but "low-moisture mozzarella" may have moisture content between 45-52%.^[Reference: https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/mozzarella-cheese]. Mozzarella cheese can be made by mixing 1 gallon of milk, 1/4 tsp of liquid rennet, cheese salt, and citric acid.

Blocks of mozzarella cheese will be made by using 4 different amounts of citric acid (1 tsp, 1.25 tsp, 1.5 tsp, 1.75 tsp) and 2 different amounts of cheese salt (1 tsp and 2 tsp).  After storage in a cooler for 3 months, the moisture content of each block will be measured at three different random locations within the block of cheese.

The researchers would like to include different types of milk as a blocking factor in their study. They went to the store and bought six different types of whole milk (e.g. from different brands, organic or not, etc.) and will run a randomized complete block design making 8 blocks of cheese from each type of milk (one block from each combination of levels of citric acid and salt). The order of mixing/making each block of cheese will be randomized within each milk type.

# Part A: Setup

**1.** Sketch a design blueprint

-   Clearly indicate the experimental units *and* measurement units
-   Clearly indicate the blocking factor (show grouping)
-   Show how treatments are assigned within blocks

**2.** Describe the treatment and experimental structures (bullets is fine!)

**3.** In one sentence, explain why blocking is preferable to using milk type as an inclusion criterion.

**4.** For the RCBD analysis that we have learned so far, how should the researchers use the three measurements from each cheese block?

**5.** Which of the following shows the *first couple of rows* of the **appropriate** data to use to analyze this study based on what we know so far?  Fill in the blanks in the statement below to describe the data.

> The appropriate data to use to analyze the cheese study is Data _______. The full dataset would have ____________ rows, where each row represents one ___________________. 

# Part B: Statistical Model

:::callout-important
For the rest of the activity, assume we have used the appropriate data for the analysis!!
:::

**6.** State the statistical effects model for a two-factorial RCBD from Module 5.

Make sure to define **all** terms, denote $i,j,m$ values, and include assumptions.

**7.** Fill in the skeleton ANOVA table for the analysis of this experiment using the RCBD analyses we have learned so far. (delete rows you don't need)

| Source of Variation                  |DF        |
|--------------------------------------|----------|
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |
|                                      |          |

# Part C: R Analysis

**7.** Fill in the appropriate *R formula* to fit the model assuming that you are using the data (called  `cheese_dat`) from Q5:

```
cheese_mod <- lm(______________________________________________________________,
                 data = cheese_dat)
```

**8.** Based on the output provided, was blocking helpful in this study? How do you know?

**9.** Based on the output provided, what is the **estimated** mean moisture content for a cheese made from the following. Show all work!

  - local organic milk
  - 1 tsp citric acid and
  - 2 tsp cheese salt

**10.** Based on the output provided, what effects should we consider for further the analysis? (e.g. interaction effects of .... main effects of ....)

**11.** Describe the nature of the interaction, if any, based on the plot below.

# Part D: Conclusions and Follow-Up

**12** Based on the analyses shown, do you have a recommendation in terms of salt and citric acid for cheese makers trying to make a mozzarella cheese with the highest moisture content?

**13.** To what population can we generalize results from this study?

**14.** Suppose the researchers were also interested in whether the effect of citric acid on the moisture depends on milk type. Why would this be difficult or impossible to assess using the current design?
